# coding: utf-8

"""
    Agora Public API

    Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from agora_public_api.models.lead_input import LeadInput
from typing import Optional, Set
from typing_extensions import Self

class LeadUploadRequest(BaseModel):
    """
    LeadUploadRequest
    """ # noqa: E501
    campaign_id: Annotated[int, Field(strict=True, ge=1)] = Field(description="Target campaign. Required for API-key-derived bearer tokens.")
    source: Optional[StrictStr] = 'api'
    leads: Annotated[List[LeadInput], Field(min_length=1)]
    tags: Optional[List[StrictStr]] = None
    skip_duplicates: Optional[StrictBool] = True
    compliance_acknowledged: StrictBool = Field(description="Must be true to confirm the caller has permission to upload these contacts.")
    disclaimer_version: Optional[StrictStr] = 'v1.0'
    __properties: ClassVar[List[str]] = ["campaign_id", "source", "leads", "tags", "skip_duplicates", "compliance_acknowledged", "disclaimer_version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LeadUploadRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in leads (list)
        _items = []
        if self.leads:
            for _item_leads in self.leads:
                if _item_leads:
                    _items.append(_item_leads.to_dict())
            _dict['leads'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LeadUploadRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "campaign_id": obj.get("campaign_id"),
            "source": obj.get("source") if obj.get("source") is not None else 'api',
            "leads": [LeadInput.from_dict(_item) for _item in obj["leads"]] if obj.get("leads") is not None else None,
            "tags": obj.get("tags"),
            "skip_duplicates": obj.get("skip_duplicates") if obj.get("skip_duplicates") is not None else True,
            "compliance_acknowledged": obj.get("compliance_acknowledged"),
            "disclaimer_version": obj.get("disclaimer_version") if obj.get("disclaimer_version") is not None else 'v1.0'
        })
        return _obj


