# coding: utf-8

"""
    Agora Public API

    Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class WebhookEndpointHealth(BaseModel):
    """
    WebhookEndpointHealth
    """ # noqa: E501
    endpoint_id: StrictInt
    url: StrictStr
    is_enabled: StrictBool
    total_deliveries: StrictInt = Field(description="Total number of delivery attempts recorded.")
    successful_deliveries: StrictInt = Field(description="Deliveries that received a 2xx response within 10 seconds.")
    failed_deliveries: StrictInt = Field(description="Deliveries that timed out or received a non-2xx response.")
    success_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ratio of successful to total deliveries (0–1). Null if no deliveries yet.")
    last_delivery_at: Optional[datetime] = Field(default=None, description="Timestamp of the most recent delivery attempt.")
    last_delivery_is_successful: Optional[StrictBool] = Field(default=None, description="Outcome of the most recent delivery attempt.")
    avg_duration_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Average round-trip time in milliseconds across all recorded deliveries.")
    __properties: ClassVar[List[str]] = ["endpoint_id", "url", "is_enabled", "total_deliveries", "successful_deliveries", "failed_deliveries", "success_rate", "last_delivery_at", "last_delivery_is_successful", "avg_duration_ms"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookEndpointHealth from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookEndpointHealth from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "endpoint_id": obj.get("endpoint_id"),
            "url": obj.get("url"),
            "is_enabled": obj.get("is_enabled"),
            "total_deliveries": obj.get("total_deliveries"),
            "successful_deliveries": obj.get("successful_deliveries"),
            "failed_deliveries": obj.get("failed_deliveries"),
            "success_rate": obj.get("success_rate"),
            "last_delivery_at": obj.get("last_delivery_at"),
            "last_delivery_is_successful": obj.get("last_delivery_is_successful"),
            "avg_duration_ms": obj.get("avg_duration_ms")
        })
        return _obj


