# coding: utf-8

"""
    Agora Public API

    Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookEndpointResponse(BaseModel):
    """
    WebhookEndpointResponse
    """ # noqa: E501
    id: StrictInt
    campaign_id: StrictInt
    url: StrictStr
    description: Optional[StrictStr] = None
    subscribed_events: List[StrictStr]
    is_enabled: StrictBool
    created_at: datetime
    secret: Optional[StrictStr] = Field(default=None, description="Signing secret. Only returned on creation — store it securely.")
    last_delivery_is_successful: Optional[StrictBool] = Field(default=None, description="Outcome of the most recent delivery attempt, or null if no deliveries yet.")
    __properties: ClassVar[List[str]] = ["id", "campaign_id", "url", "description", "subscribed_events", "is_enabled", "created_at", "secret", "last_delivery_is_successful"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookEndpointResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookEndpointResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "campaign_id": obj.get("campaign_id"),
            "url": obj.get("url"),
            "description": obj.get("description"),
            "subscribed_events": obj.get("subscribed_events"),
            "is_enabled": obj.get("is_enabled"),
            "created_at": obj.get("created_at"),
            "secret": obj.get("secret"),
            "last_delivery_is_successful": obj.get("last_delivery_is_successful")
        })
        return _obj


