# coding: utf-8

"""
    Agora Public API

    Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

    The version of the OpenAPI document: 1.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class WebhookDeliveryResponse(BaseModel):
    """
    WebhookDeliveryResponse
    """ # noqa: E501
    id: StrictInt
    endpoint_id: StrictInt
    event_type: StrictStr
    payload: Dict[str, Any] = Field(description="Full JSON payload that was sent to the endpoint.")
    response_status: Optional[StrictInt] = Field(default=None, description="HTTP status code returned by the endpoint, or null if the request failed to connect.")
    response_body: Optional[StrictStr] = Field(default=None, description="First 1 KB of the response body.")
    duration_ms: Optional[StrictInt] = Field(default=None, description="Round-trip time in milliseconds.")
    is_successful: StrictBool = Field(description="True if the endpoint returned a 2xx status within 10 seconds.")
    attempt_number: StrictInt = Field(description="1 for the original delivery, 2 for the automatic retry.")
    delivered_at: datetime
    redelivery_of_id: Optional[StrictInt] = Field(default=None, description="ID of the original delivery if this is a manual redeliver, otherwise null.")
    __properties: ClassVar[List[str]] = ["id", "endpoint_id", "event_type", "payload", "response_status", "response_body", "duration_ms", "is_successful", "attempt_number", "delivered_at", "redelivery_of_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WebhookDeliveryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WebhookDeliveryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "endpoint_id": obj.get("endpoint_id"),
            "event_type": obj.get("event_type"),
            "payload": obj.get("payload"),
            "response_status": obj.get("response_status"),
            "response_body": obj.get("response_body"),
            "duration_ms": obj.get("duration_ms"),
            "is_successful": obj.get("is_successful"),
            "attempt_number": obj.get("attempt_number"),
            "delivered_at": obj.get("delivered_at"),
            "redelivery_of_id": obj.get("redelivery_of_id")
        })
        return _obj


