nodeLinker: pnp
enableGlobalCache: true

packageExtensions:
  "@semantic-release/commit-analyzer@*":
    dependencies:
      conventional-changelog-conventionalcommits: "*"
  "@semantic-release/release-notes-generator@*":
    dependencies:
      conventional-changelog-conventionalcommits: "*"
