module.exports = {
  branches: ["main"],
  tagFormat: "v${version}",
  plugins: [
    ["@semantic-release/commit-analyzer", { preset: "conventionalcommits" }],
    ["@semantic-release/release-notes-generator", { preset: "conventionalcommits" }],
    ["@semantic-release/changelog", { changelogFile: "CHANGELOG.md" }],
    [
      "@semantic-release/exec",
      {
        verifyReleaseCmd: "yarn release:verify",
        prepareCmd: "yarn release:prepare ${nextRelease.version}"
      }
    ],
    [
      "@semantic-release/git",
      {
        assets: [
          "CHANGELOG.md",
          "package.json",
          "openapi/agora-public-api.yaml",
          "sdks/typescript/package.json",
          "sdks/python/pyproject.toml",
          "sdks/java/pom.xml"
        ],
        message: "chore(release): ${nextRelease.version}\n\nAutomatically generated by semantic-release"
      }
    ],
    "@semantic-release/github"
  ]
};
