/*
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.agora.publicapi.api;

import ai.agora.publicapi.ApiCallback;
import ai.agora.publicapi.ApiClient;
import ai.agora.publicapi.ApiException;
import ai.agora.publicapi.ApiResponse;
import ai.agora.publicapi.Configuration;
import ai.agora.publicapi.Pair;
import ai.agora.publicapi.ProgressRequestBody;
import ai.agora.publicapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.agora.publicapi.model.ApiKeyTokenRequest;
import ai.agora.publicapi.model.ApiKeyTokenResponse;
import ai.agora.publicapi.model.ErrorResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class AuthenticationApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public AuthenticationApi() {
        this(Configuration.getDefaultApiClient());
    }

    public AuthenticationApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for loginWithApiKey
     * @param apiKeyTokenRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Short-lived bearer token. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The API key is invalid, expired, or revoked. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginWithApiKeyCall(ApiKeyTokenRequest apiKeyTokenRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = apiKeyTokenRequest;

        // create path and map variables
        String localVarPath = "/auth/api-key/token";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call loginWithApiKeyValidateBeforeCall(ApiKeyTokenRequest apiKeyTokenRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'apiKeyTokenRequest' is set
        if (apiKeyTokenRequest == null) {
            throw new ApiException("Missing the required parameter 'apiKeyTokenRequest' when calling loginWithApiKey(Async)");
        }

        return loginWithApiKeyCall(apiKeyTokenRequest, _callback);

    }

    /**
     * Log in with an API key
     * Logs in with a long-lived Agora API key and returns a short-lived bearer JWT. The API key is only sent to this endpoint and should not be used for normal API calls.
     * @param apiKeyTokenRequest  (required)
     * @return ApiKeyTokenResponse
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Short-lived bearer token. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The API key is invalid, expired, or revoked. </td><td>  -  </td></tr>
     </table>
     */
    public ApiKeyTokenResponse loginWithApiKey(ApiKeyTokenRequest apiKeyTokenRequest) throws ApiException {
        ApiResponse<ApiKeyTokenResponse> localVarResp = loginWithApiKeyWithHttpInfo(apiKeyTokenRequest);
        return localVarResp.getData();
    }

    /**
     * Log in with an API key
     * Logs in with a long-lived Agora API key and returns a short-lived bearer JWT. The API key is only sent to this endpoint and should not be used for normal API calls.
     * @param apiKeyTokenRequest  (required)
     * @return ApiResponse&lt;ApiKeyTokenResponse&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Short-lived bearer token. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The API key is invalid, expired, or revoked. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<ApiKeyTokenResponse> loginWithApiKeyWithHttpInfo(ApiKeyTokenRequest apiKeyTokenRequest) throws ApiException {
        okhttp3.Call localVarCall = loginWithApiKeyValidateBeforeCall(apiKeyTokenRequest, null);
        Type localVarReturnType = new TypeToken<ApiKeyTokenResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Log in with an API key (asynchronously)
     * Logs in with a long-lived Agora API key and returns a short-lived bearer JWT. The API key is only sent to this endpoint and should not be used for normal API calls.
     * @param apiKeyTokenRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Short-lived bearer token. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> The API key is invalid, expired, or revoked. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call loginWithApiKeyAsync(ApiKeyTokenRequest apiKeyTokenRequest, final ApiCallback<ApiKeyTokenResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = loginWithApiKeyValidateBeforeCall(apiKeyTokenRequest, _callback);
        Type localVarReturnType = new TypeToken<ApiKeyTokenResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
