/*
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.agora.publicapi.api;

import ai.agora.publicapi.ApiCallback;
import ai.agora.publicapi.ApiClient;
import ai.agora.publicapi.ApiException;
import ai.agora.publicapi.ApiResponse;
import ai.agora.publicapi.Configuration;
import ai.agora.publicapi.Pair;
import ai.agora.publicapi.ProgressRequestBody;
import ai.agora.publicapi.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import ai.agora.publicapi.model.ErrorResponse;
import ai.agora.publicapi.model.WebhookEndpointHealth;
import ai.agora.publicapi.model.WebhookEndpointSummary;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class WebhooksApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public WebhooksApi() {
        this(Configuration.getDefaultApiClient());
    }

    public WebhooksApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getWebhookEndpointHealth
     * @param campaignId ID of the campaign. (required)
     * @param endpointId ID of the webhook endpoint. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Delivery health snapshot. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found or does not belong to this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWebhookEndpointHealthCall(Integer campaignId, Integer endpointId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/{campaign_id}/endpoints/{endpoint_id}/health"
            .replace("{" + "campaign_id" + "}", localVarApiClient.escapeString(campaignId.toString()))
            .replace("{" + "endpoint_id" + "}", localVarApiClient.escapeString(endpointId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getWebhookEndpointHealthValidateBeforeCall(Integer campaignId, Integer endpointId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'campaignId' is set
        if (campaignId == null) {
            throw new ApiException("Missing the required parameter 'campaignId' when calling getWebhookEndpointHealth(Async)");
        }

        // verify the required parameter 'endpointId' is set
        if (endpointId == null) {
            throw new ApiException("Missing the required parameter 'endpointId' when calling getWebhookEndpointHealth(Async)");
        }

        return getWebhookEndpointHealthCall(campaignId, endpointId, _callback);

    }

    /**
     * Get delivery health for a webhook endpoint
     * Returns a delivery health snapshot for the endpoint: total/successful/failed delivery counts, success rate, last delivery timestamp, and average response time. Use this to monitor the reliability of your webhook integration — alert on a dropping success rate or a stale &#x60;last_delivery_at&#x60;. 
     * @param campaignId ID of the campaign. (required)
     * @param endpointId ID of the webhook endpoint. (required)
     * @return WebhookEndpointHealth
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Delivery health snapshot. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found or does not belong to this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public WebhookEndpointHealth getWebhookEndpointHealth(Integer campaignId, Integer endpointId) throws ApiException {
        ApiResponse<WebhookEndpointHealth> localVarResp = getWebhookEndpointHealthWithHttpInfo(campaignId, endpointId);
        return localVarResp.getData();
    }

    /**
     * Get delivery health for a webhook endpoint
     * Returns a delivery health snapshot for the endpoint: total/successful/failed delivery counts, success rate, last delivery timestamp, and average response time. Use this to monitor the reliability of your webhook integration — alert on a dropping success rate or a stale &#x60;last_delivery_at&#x60;. 
     * @param campaignId ID of the campaign. (required)
     * @param endpointId ID of the webhook endpoint. (required)
     * @return ApiResponse&lt;WebhookEndpointHealth&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Delivery health snapshot. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found or does not belong to this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<WebhookEndpointHealth> getWebhookEndpointHealthWithHttpInfo(Integer campaignId, Integer endpointId) throws ApiException {
        okhttp3.Call localVarCall = getWebhookEndpointHealthValidateBeforeCall(campaignId, endpointId, null);
        Type localVarReturnType = new TypeToken<WebhookEndpointHealth>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get delivery health for a webhook endpoint (asynchronously)
     * Returns a delivery health snapshot for the endpoint: total/successful/failed delivery counts, success rate, last delivery timestamp, and average response time. Use this to monitor the reliability of your webhook integration — alert on a dropping success rate or a stale &#x60;last_delivery_at&#x60;. 
     * @param campaignId ID of the campaign. (required)
     * @param endpointId ID of the webhook endpoint. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Delivery health snapshot. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Resource not found or does not belong to this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getWebhookEndpointHealthAsync(Integer campaignId, Integer endpointId, final ApiCallback<WebhookEndpointHealth> _callback) throws ApiException {

        okhttp3.Call localVarCall = getWebhookEndpointHealthValidateBeforeCall(campaignId, endpointId, _callback);
        Type localVarReturnType = new TypeToken<WebhookEndpointHealth>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWebhookEndpoints
     * @param campaignId ID of the campaign. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhook endpoints. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhookEndpointsCall(Integer campaignId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/{campaign_id}/endpoints"
            .replace("{" + "campaign_id" + "}", localVarApiClient.escapeString(campaignId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWebhookEndpointsValidateBeforeCall(Integer campaignId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'campaignId' is set
        if (campaignId == null) {
            throw new ApiException("Missing the required parameter 'campaignId' when calling listWebhookEndpoints(Async)");
        }

        return listWebhookEndpointsCall(campaignId, _callback);

    }

    /**
     * List webhook endpoints
     * Returns all webhook endpoints configured on a campaign. Does not include signing secrets — use the Agora dashboard to manage secrets.
     * @param campaignId ID of the campaign. (required)
     * @return List&lt;WebhookEndpointSummary&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhook endpoints. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public List<WebhookEndpointSummary> listWebhookEndpoints(Integer campaignId) throws ApiException {
        ApiResponse<List<WebhookEndpointSummary>> localVarResp = listWebhookEndpointsWithHttpInfo(campaignId);
        return localVarResp.getData();
    }

    /**
     * List webhook endpoints
     * Returns all webhook endpoints configured on a campaign. Does not include signing secrets — use the Agora dashboard to manage secrets.
     * @param campaignId ID of the campaign. (required)
     * @return ApiResponse&lt;List&lt;WebhookEndpointSummary&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhook endpoints. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<WebhookEndpointSummary>> listWebhookEndpointsWithHttpInfo(Integer campaignId) throws ApiException {
        okhttp3.Call localVarCall = listWebhookEndpointsValidateBeforeCall(campaignId, null);
        Type localVarReturnType = new TypeToken<List<WebhookEndpointSummary>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List webhook endpoints (asynchronously)
     * Returns all webhook endpoints configured on a campaign. Does not include signing secrets — use the Agora dashboard to manage secrets.
     * @param campaignId ID of the campaign. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> List of webhook endpoints. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhookEndpointsAsync(Integer campaignId, final ApiCallback<List<WebhookEndpointSummary>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWebhookEndpointsValidateBeforeCall(campaignId, _callback);
        Type localVarReturnType = new TypeToken<List<WebhookEndpointSummary>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for listWebhookEventTypes
     * @param campaignId ID of the campaign. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of event type strings. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhookEventTypesCall(Integer campaignId, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/webhooks/{campaign_id}/events"
            .replace("{" + "campaign_id" + "}", localVarApiClient.escapeString(campaignId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "bearerAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call listWebhookEventTypesValidateBeforeCall(Integer campaignId, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'campaignId' is set
        if (campaignId == null) {
            throw new ApiException("Missing the required parameter 'campaignId' when calling listWebhookEventTypes(Async)");
        }

        return listWebhookEventTypesCall(campaignId, _callback);

    }

    /**
     * List webhook event types
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * @param campaignId ID of the campaign. (required)
     * @return List&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of event type strings. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public List<String> listWebhookEventTypes(Integer campaignId) throws ApiException {
        ApiResponse<List<String>> localVarResp = listWebhookEventTypesWithHttpInfo(campaignId);
        return localVarResp.getData();
    }

    /**
     * List webhook event types
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * @param campaignId ID of the campaign. (required)
     * @return ApiResponse&lt;List&lt;String&gt;&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of event type strings. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<List<String>> listWebhookEventTypesWithHttpInfo(Integer campaignId) throws ApiException {
        okhttp3.Call localVarCall = listWebhookEventTypesValidateBeforeCall(campaignId, null);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * List webhook event types (asynchronously)
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * @param campaignId ID of the campaign. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Array of event type strings. </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Missing, invalid, or expired bearer token. </td><td>  -  </td></tr>
        <tr><td> 403 </td><td> Bearer token is not authorized for this campaign. </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call listWebhookEventTypesAsync(Integer campaignId, final ApiCallback<List<String>> _callback) throws ApiException {

        okhttp3.Call localVarCall = listWebhookEventTypesValidateBeforeCall(campaignId, _callback);
        Type localVarReturnType = new TypeToken<List<String>>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
