/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyTokenResponse
 */
export interface ApiKeyTokenResponse {
    /**
     * Short-lived bearer JWT. Do not log this value.
     * @type {string}
     * @memberof ApiKeyTokenResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof ApiKeyTokenResponse
     */
    tokenType: ApiKeyTokenResponseTokenTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ApiKeyTokenResponse
     */
    expiresIn: number;
}


/**
 * @export
 */
export const ApiKeyTokenResponseTokenTypeEnum = {
    Bearer: 'Bearer'
} as const;
export type ApiKeyTokenResponseTokenTypeEnum = typeof ApiKeyTokenResponseTokenTypeEnum[keyof typeof ApiKeyTokenResponseTokenTypeEnum];


/**
 * Check if a given object implements the ApiKeyTokenResponse interface.
 */
export function instanceOfApiKeyTokenResponse(value: object): value is ApiKeyTokenResponse {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('tokenType' in value) || value['tokenType'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    return true;
}

export function ApiKeyTokenResponseFromJSON(json: any): ApiKeyTokenResponse {
    return ApiKeyTokenResponseFromJSONTyped(json, false);
}

export function ApiKeyTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
    };
}

export function ApiKeyTokenResponseToJSON(json: any): ApiKeyTokenResponse {
    return ApiKeyTokenResponseToJSONTyped(json, false);
}

export function ApiKeyTokenResponseToJSONTyped(value?: ApiKeyTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
    };
}

