/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyTokenRequest
 */
export interface ApiKeyTokenRequest {
    /**
     * Agora API key. Never log or persist this value outside secure credential storage.
     * @type {string}
     * @memberof ApiKeyTokenRequest
     */
    apiKey: string;
}

/**
 * Check if a given object implements the ApiKeyTokenRequest interface.
 */
export function instanceOfApiKeyTokenRequest(value: object): value is ApiKeyTokenRequest {
    if (!('apiKey' in value) || value['apiKey'] === undefined) return false;
    return true;
}

export function ApiKeyTokenRequestFromJSON(json: any): ApiKeyTokenRequest {
    return ApiKeyTokenRequestFromJSONTyped(json, false);
}

export function ApiKeyTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'apiKey': json['api_key'],
    };
}

export function ApiKeyTokenRequestToJSON(json: any): ApiKeyTokenRequest {
    return ApiKeyTokenRequestToJSONTyped(json, false);
}

export function ApiKeyTokenRequestToJSONTyped(value?: ApiKeyTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'api_key': value['apiKey'],
    };
}

