/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeadUploadError
 */
export interface LeadUploadError {
    /**
     * 
     * @type {number}
     * @memberof LeadUploadError
     */
    row: number;
    /**
     * 
     * @type {string}
     * @memberof LeadUploadError
     */
    field?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LeadUploadError
     */
    message: string;
}

/**
 * Check if a given object implements the LeadUploadError interface.
 */
export function instanceOfLeadUploadError(value: object): value is LeadUploadError {
    if (!('row' in value) || value['row'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function LeadUploadErrorFromJSON(json: any): LeadUploadError {
    return LeadUploadErrorFromJSONTyped(json, false);
}

export function LeadUploadErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeadUploadError {
    if (json == null) {
        return json;
    }
    return {
        
        'row': json['row'],
        'field': json['field'] == null ? undefined : json['field'],
        'message': json['message'],
    };
}

export function LeadUploadErrorToJSON(json: any): LeadUploadError {
    return LeadUploadErrorToJSONTyped(json, false);
}

export function LeadUploadErrorToJSONTyped(value?: LeadUploadError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row': value['row'],
        'field': value['field'],
        'message': value['message'],
    };
}

