/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeadInput } from './LeadInput';
import {
    LeadInputFromJSON,
    LeadInputFromJSONTyped,
    LeadInputToJSON,
    LeadInputToJSONTyped,
} from './LeadInput';

/**
 * 
 * @export
 * @interface LeadUploadRequest
 */
export interface LeadUploadRequest {
    /**
     * Target campaign. Required for API-key-derived bearer tokens.
     * @type {number}
     * @memberof LeadUploadRequest
     */
    campaignId: number;
    /**
     * 
     * @type {string}
     * @memberof LeadUploadRequest
     */
    source?: string;
    /**
     * 
     * @type {Array<LeadInput>}
     * @memberof LeadUploadRequest
     */
    leads: Array<LeadInput>;
    /**
     * 
     * @type {Array<string>}
     * @memberof LeadUploadRequest
     */
    tags?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof LeadUploadRequest
     */
    skipDuplicates?: boolean;
    /**
     * Must be true to confirm the caller has permission to upload these contacts.
     * @type {boolean}
     * @memberof LeadUploadRequest
     */
    complianceAcknowledged: boolean;
    /**
     * 
     * @type {string}
     * @memberof LeadUploadRequest
     */
    disclaimerVersion?: string;
}

/**
 * Check if a given object implements the LeadUploadRequest interface.
 */
export function instanceOfLeadUploadRequest(value: object): value is LeadUploadRequest {
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('leads' in value) || value['leads'] === undefined) return false;
    if (!('complianceAcknowledged' in value) || value['complianceAcknowledged'] === undefined) return false;
    return true;
}

export function LeadUploadRequestFromJSON(json: any): LeadUploadRequest {
    return LeadUploadRequestFromJSONTyped(json, false);
}

export function LeadUploadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeadUploadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'campaignId': json['campaign_id'],
        'source': json['source'] == null ? undefined : json['source'],
        'leads': ((json['leads'] as Array<any>).map(LeadInputFromJSON)),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'skipDuplicates': json['skip_duplicates'] == null ? undefined : json['skip_duplicates'],
        'complianceAcknowledged': json['compliance_acknowledged'],
        'disclaimerVersion': json['disclaimer_version'] == null ? undefined : json['disclaimer_version'],
    };
}

export function LeadUploadRequestToJSON(json: any): LeadUploadRequest {
    return LeadUploadRequestToJSONTyped(json, false);
}

export function LeadUploadRequestToJSONTyped(value?: LeadUploadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'campaign_id': value['campaignId'],
        'source': value['source'],
        'leads': ((value['leads'] as Array<any>).map(LeadInputToJSON)),
        'tags': value['tags'],
        'skip_duplicates': value['skipDuplicates'],
        'compliance_acknowledged': value['complianceAcknowledged'],
        'disclaimer_version': value['disclaimerVersion'],
    };
}

