/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeadInput
 */
export interface LeadInput {
    /**
     * 
     * @type {string}
     * @memberof LeadInput
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof LeadInput
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof LeadInput
     */
    email?: string;
    /**
     * E.164 formatted phone number is preferred.
     * @type {string}
     * @memberof LeadInput
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof LeadInput
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof LeadInput
     */
    title?: string;
}

/**
 * Check if a given object implements the LeadInput interface.
 */
export function instanceOfLeadInput(value: object): value is LeadInput {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    return true;
}

export function LeadInputFromJSON(json: any): LeadInput {
    return LeadInputFromJSONTyped(json, false);
}

export function LeadInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeadInput {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'],
        'company': json['company'] == null ? undefined : json['company'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function LeadInputToJSON(json: any): LeadInput {
    return LeadInputToJSONTyped(json, false);
}

export function LeadInputToJSONTyped(value?: LeadInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone': value['phone'],
        'company': value['company'],
        'title': value['title'],
    };
}

