/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LeadUploadError } from './LeadUploadError';
import {
    LeadUploadErrorFromJSON,
    LeadUploadErrorFromJSONTyped,
    LeadUploadErrorToJSON,
    LeadUploadErrorToJSONTyped,
} from './LeadUploadError';

/**
 * 
 * @export
 * @interface LeadUploadResponse
 */
export interface LeadUploadResponse {
    /**
     * 
     * @type {string}
     * @memberof LeadUploadResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof LeadUploadResponse
     */
    importId: string;
    /**
     * 
     * @type {number}
     * @memberof LeadUploadResponse
     */
    receivedCount: number;
    /**
     * 
     * @type {number}
     * @memberof LeadUploadResponse
     */
    validCount: number;
    /**
     * 
     * @type {number}
     * @memberof LeadUploadResponse
     */
    invalidCount: number;
    /**
     * 
     * @type {Array<LeadUploadError>}
     * @memberof LeadUploadResponse
     */
    errors: Array<LeadUploadError>;
}

/**
 * Check if a given object implements the LeadUploadResponse interface.
 */
export function instanceOfLeadUploadResponse(value: object): value is LeadUploadResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('importId' in value) || value['importId'] === undefined) return false;
    if (!('receivedCount' in value) || value['receivedCount'] === undefined) return false;
    if (!('validCount' in value) || value['validCount'] === undefined) return false;
    if (!('invalidCount' in value) || value['invalidCount'] === undefined) return false;
    if (!('errors' in value) || value['errors'] === undefined) return false;
    return true;
}

export function LeadUploadResponseFromJSON(json: any): LeadUploadResponse {
    return LeadUploadResponseFromJSONTyped(json, false);
}

export function LeadUploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeadUploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'importId': json['import_id'],
        'receivedCount': json['received_count'],
        'validCount': json['valid_count'],
        'invalidCount': json['invalid_count'],
        'errors': ((json['errors'] as Array<any>).map(LeadUploadErrorFromJSON)),
    };
}

export function LeadUploadResponseToJSON(json: any): LeadUploadResponse {
    return LeadUploadResponseToJSONTyped(json, false);
}

export function LeadUploadResponseToJSONTyped(value?: LeadUploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'import_id': value['importId'],
        'received_count': value['receivedCount'],
        'valid_count': value['validCount'],
        'invalid_count': value['invalidCount'],
        'errors': ((value['errors'] as Array<any>).map(LeadUploadErrorToJSON)),
    };
}

