/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegenerateSecretResponse
 */
export interface RegenerateSecretResponse {
    /**
     * New HMAC-SHA256 signing secret. Store securely — not shown again.
     * @type {string}
     * @memberof RegenerateSecretResponse
     */
    secret: string;
}

/**
 * Check if a given object implements the RegenerateSecretResponse interface.
 */
export function instanceOfRegenerateSecretResponse(value: object): value is RegenerateSecretResponse {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function RegenerateSecretResponseFromJSON(json: any): RegenerateSecretResponse {
    return RegenerateSecretResponseFromJSONTyped(json, false);
}

export function RegenerateSecretResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegenerateSecretResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
    };
}

export function RegenerateSecretResponseToJSON(json: any): RegenerateSecretResponse {
    return RegenerateSecretResponseToJSONTyped(json, false);
}

export function RegenerateSecretResponseToJSONTyped(value?: RegenerateSecretResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secret': value['secret'],
    };
}

