/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDeliveryResponse
 */
export interface WebhookDeliveryResponse {
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    endpointId: number;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponse
     */
    eventType: string;
    /**
     * Full JSON payload that was sent to the endpoint.
     * @type {object}
     * @memberof WebhookDeliveryResponse
     */
    payload: object;
    /**
     * HTTP status code returned by the endpoint, or null if the request failed to connect.
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    responseStatus?: number;
    /**
     * First 1 KB of the response body.
     * @type {string}
     * @memberof WebhookDeliveryResponse
     */
    responseBody?: string;
    /**
     * Round-trip time in milliseconds.
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    durationMs?: number;
    /**
     * True if the endpoint returned a 2xx status within 10 seconds.
     * @type {boolean}
     * @memberof WebhookDeliveryResponse
     */
    isSuccessful: boolean;
    /**
     * 1 for the original delivery, 2 for the automatic retry.
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    attemptNumber: number;
    /**
     * 
     * @type {Date}
     * @memberof WebhookDeliveryResponse
     */
    deliveredAt: Date;
    /**
     * ID of the original delivery if this is a manual redeliver, otherwise null.
     * @type {number}
     * @memberof WebhookDeliveryResponse
     */
    redeliveryOfId?: number;
}

/**
 * Check if a given object implements the WebhookDeliveryResponse interface.
 */
export function instanceOfWebhookDeliveryResponse(value: object): value is WebhookDeliveryResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('endpointId' in value) || value['endpointId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('attemptNumber' in value) || value['attemptNumber'] === undefined) return false;
    if (!('deliveredAt' in value) || value['deliveredAt'] === undefined) return false;
    return true;
}

export function WebhookDeliveryResponseFromJSON(json: any): WebhookDeliveryResponse {
    return WebhookDeliveryResponseFromJSONTyped(json, false);
}

export function WebhookDeliveryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'endpointId': json['endpoint_id'],
        'eventType': json['event_type'],
        'payload': json['payload'],
        'responseStatus': json['response_status'] == null ? undefined : json['response_status'],
        'responseBody': json['response_body'] == null ? undefined : json['response_body'],
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'isSuccessful': json['is_successful'],
        'attemptNumber': json['attempt_number'],
        'deliveredAt': (new Date(json['delivered_at'])),
        'redeliveryOfId': json['redelivery_of_id'] == null ? undefined : json['redelivery_of_id'],
    };
}

export function WebhookDeliveryResponseToJSON(json: any): WebhookDeliveryResponse {
    return WebhookDeliveryResponseToJSONTyped(json, false);
}

export function WebhookDeliveryResponseToJSONTyped(value?: WebhookDeliveryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'endpoint_id': value['endpointId'],
        'event_type': value['eventType'],
        'payload': value['payload'],
        'response_status': value['responseStatus'],
        'response_body': value['responseBody'],
        'duration_ms': value['durationMs'],
        'is_successful': value['isSuccessful'],
        'attempt_number': value['attemptNumber'],
        'delivered_at': ((value['deliveredAt']).toISOString()),
        'redelivery_of_id': value['redeliveryOfId'],
    };
}

