/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointCreate
 */
export interface WebhookEndpointCreate {
    /**
     * HTTPS URL Agora will POST events to.
     * @type {string}
     * @memberof WebhookEndpointCreate
     */
    url: string;
    /**
     * Optional human-readable label for this endpoint.
     * @type {string}
     * @memberof WebhookEndpointCreate
     */
    description?: string;
    /**
     * Event types to subscribe to. Use `listWebhookEventTypes` for valid values.
     * @type {Array<string>}
     * @memberof WebhookEndpointCreate
     */
    subscribedEvents?: Array<string>;
    /**
     * Whether the endpoint should receive deliveries.
     * @type {boolean}
     * @memberof WebhookEndpointCreate
     */
    isEnabled?: boolean;
}

/**
 * Check if a given object implements the WebhookEndpointCreate interface.
 */
export function instanceOfWebhookEndpointCreate(value: object): value is WebhookEndpointCreate {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function WebhookEndpointCreateFromJSON(json: any): WebhookEndpointCreate {
    return WebhookEndpointCreateFromJSONTyped(json, false);
}

export function WebhookEndpointCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'subscribedEvents': json['subscribed_events'] == null ? undefined : json['subscribed_events'],
        'isEnabled': json['is_enabled'] == null ? undefined : json['is_enabled'],
    };
}

export function WebhookEndpointCreateToJSON(json: any): WebhookEndpointCreate {
    return WebhookEndpointCreateToJSONTyped(json, false);
}

export function WebhookEndpointCreateToJSONTyped(value?: WebhookEndpointCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'description': value['description'],
        'subscribed_events': value['subscribedEvents'],
        'is_enabled': value['isEnabled'],
    };
}

