/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointResponse
 */
export interface WebhookEndpointResponse {
    /**
     * 
     * @type {number}
     * @memberof WebhookEndpointResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof WebhookEndpointResponse
     */
    campaignId: number;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponse
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponse
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebhookEndpointResponse
     */
    subscribedEvents: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpointResponse
     */
    isEnabled: boolean;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEndpointResponse
     */
    createdAt: Date;
    /**
     * Signing secret. Only returned on creation — store it securely.
     * @type {string}
     * @memberof WebhookEndpointResponse
     */
    secret?: string;
    /**
     * Outcome of the most recent delivery attempt, or null if no deliveries yet.
     * @type {boolean}
     * @memberof WebhookEndpointResponse
     */
    lastDeliveryIsSuccessful?: boolean;
}

/**
 * Check if a given object implements the WebhookEndpointResponse interface.
 */
export function instanceOfWebhookEndpointResponse(value: object): value is WebhookEndpointResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('campaignId' in value) || value['campaignId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('subscribedEvents' in value) || value['subscribedEvents'] === undefined) return false;
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function WebhookEndpointResponseFromJSON(json: any): WebhookEndpointResponse {
    return WebhookEndpointResponseFromJSONTyped(json, false);
}

export function WebhookEndpointResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'campaignId': json['campaign_id'],
        'url': json['url'],
        'description': json['description'] == null ? undefined : json['description'],
        'subscribedEvents': json['subscribed_events'],
        'isEnabled': json['is_enabled'],
        'createdAt': (new Date(json['created_at'])),
        'secret': json['secret'] == null ? undefined : json['secret'],
        'lastDeliveryIsSuccessful': json['last_delivery_is_successful'] == null ? undefined : json['last_delivery_is_successful'],
    };
}

export function WebhookEndpointResponseToJSON(json: any): WebhookEndpointResponse {
    return WebhookEndpointResponseToJSONTyped(json, false);
}

export function WebhookEndpointResponseToJSONTyped(value?: WebhookEndpointResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'campaign_id': value['campaignId'],
        'url': value['url'],
        'description': value['description'],
        'subscribed_events': value['subscribedEvents'],
        'is_enabled': value['isEnabled'],
        'created_at': ((value['createdAt']).toISOString()),
        'secret': value['secret'],
        'last_delivery_is_successful': value['lastDeliveryIsSuccessful'],
    };
}

