/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointHealth
 */
export interface WebhookEndpointHealth {
    /**
     * 
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    endpointId: number;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointHealth
     */
    url: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpointHealth
     */
    isEnabled: boolean;
    /**
     * Total number of delivery attempts recorded.
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    totalDeliveries: number;
    /**
     * Deliveries that received a 2xx response within 10 seconds.
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    successfulDeliveries: number;
    /**
     * Deliveries that timed out or received a non-2xx response.
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    failedDeliveries: number;
    /**
     * Ratio of successful to total deliveries (0–1). Null if no deliveries yet.
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    successRate?: number;
    /**
     * Timestamp of the most recent delivery attempt.
     * @type {Date}
     * @memberof WebhookEndpointHealth
     */
    lastDeliveryAt?: Date;
    /**
     * Outcome of the most recent delivery attempt.
     * @type {boolean}
     * @memberof WebhookEndpointHealth
     */
    lastDeliveryIsSuccessful?: boolean;
    /**
     * Average round-trip time in milliseconds across all recorded deliveries.
     * @type {number}
     * @memberof WebhookEndpointHealth
     */
    avgDurationMs?: number;
}

/**
 * Check if a given object implements the WebhookEndpointHealth interface.
 */
export function instanceOfWebhookEndpointHealth(value: object): value is WebhookEndpointHealth {
    if (!('endpointId' in value) || value['endpointId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('isEnabled' in value) || value['isEnabled'] === undefined) return false;
    if (!('totalDeliveries' in value) || value['totalDeliveries'] === undefined) return false;
    if (!('successfulDeliveries' in value) || value['successfulDeliveries'] === undefined) return false;
    if (!('failedDeliveries' in value) || value['failedDeliveries'] === undefined) return false;
    return true;
}

export function WebhookEndpointHealthFromJSON(json: any): WebhookEndpointHealth {
    return WebhookEndpointHealthFromJSONTyped(json, false);
}

export function WebhookEndpointHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointHealth {
    if (json == null) {
        return json;
    }
    return {
        
        'endpointId': json['endpoint_id'],
        'url': json['url'],
        'isEnabled': json['is_enabled'],
        'totalDeliveries': json['total_deliveries'],
        'successfulDeliveries': json['successful_deliveries'],
        'failedDeliveries': json['failed_deliveries'],
        'successRate': json['success_rate'] == null ? undefined : json['success_rate'],
        'lastDeliveryAt': json['last_delivery_at'] == null ? undefined : (new Date(json['last_delivery_at'])),
        'lastDeliveryIsSuccessful': json['last_delivery_is_successful'] == null ? undefined : json['last_delivery_is_successful'],
        'avgDurationMs': json['avg_duration_ms'] == null ? undefined : json['avg_duration_ms'],
    };
}

export function WebhookEndpointHealthToJSON(json: any): WebhookEndpointHealth {
    return WebhookEndpointHealthToJSONTyped(json, false);
}

export function WebhookEndpointHealthToJSONTyped(value?: WebhookEndpointHealth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint_id': value['endpointId'],
        'url': value['url'],
        'is_enabled': value['isEnabled'],
        'total_deliveries': value['totalDeliveries'],
        'successful_deliveries': value['successfulDeliveries'],
        'failed_deliveries': value['failedDeliveries'],
        'success_rate': value['successRate'],
        'last_delivery_at': value['lastDeliveryAt'] == null ? undefined : ((value['lastDeliveryAt']).toISOString()),
        'last_delivery_is_successful': value['lastDeliveryIsSuccessful'],
        'avg_duration_ms': value['avgDurationMs'],
    };
}

