/*
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.agora.publicapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.agora.publicapi.JSON;

/**
 * WebhookDeliveryResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T17:25:58.394254106Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class WebhookDeliveryResponse {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private Integer id;

  public static final String SERIALIZED_NAME_ENDPOINT_ID = "endpoint_id";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_ID)
  @javax.annotation.Nonnull
  private Integer endpointId;

  public static final String SERIALIZED_NAME_EVENT_TYPE = "event_type";
  @SerializedName(SERIALIZED_NAME_EVENT_TYPE)
  @javax.annotation.Nonnull
  private String eventType;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  @javax.annotation.Nonnull
  private Object payload;

  public static final String SERIALIZED_NAME_RESPONSE_STATUS = "response_status";
  @SerializedName(SERIALIZED_NAME_RESPONSE_STATUS)
  @javax.annotation.Nullable
  private Integer responseStatus;

  public static final String SERIALIZED_NAME_RESPONSE_BODY = "response_body";
  @SerializedName(SERIALIZED_NAME_RESPONSE_BODY)
  @javax.annotation.Nullable
  private String responseBody;

  public static final String SERIALIZED_NAME_DURATION_MS = "duration_ms";
  @SerializedName(SERIALIZED_NAME_DURATION_MS)
  @javax.annotation.Nullable
  private Integer durationMs;

  public static final String SERIALIZED_NAME_IS_SUCCESSFUL = "is_successful";
  @SerializedName(SERIALIZED_NAME_IS_SUCCESSFUL)
  @javax.annotation.Nonnull
  private Boolean isSuccessful;

  public static final String SERIALIZED_NAME_ATTEMPT_NUMBER = "attempt_number";
  @SerializedName(SERIALIZED_NAME_ATTEMPT_NUMBER)
  @javax.annotation.Nonnull
  private Integer attemptNumber;

  public static final String SERIALIZED_NAME_DELIVERED_AT = "delivered_at";
  @SerializedName(SERIALIZED_NAME_DELIVERED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime deliveredAt;

  public static final String SERIALIZED_NAME_REDELIVERY_OF_ID = "redelivery_of_id";
  @SerializedName(SERIALIZED_NAME_REDELIVERY_OF_ID)
  @javax.annotation.Nullable
  private Integer redeliveryOfId;

  public WebhookDeliveryResponse() {
  }

  public WebhookDeliveryResponse id(@javax.annotation.Nonnull Integer id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public Integer getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull Integer id) {
    this.id = id;
  }


  public WebhookDeliveryResponse endpointId(@javax.annotation.Nonnull Integer endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @javax.annotation.Nonnull
  public Integer getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(@javax.annotation.Nonnull Integer endpointId) {
    this.endpointId = endpointId;
  }


  public WebhookDeliveryResponse eventType(@javax.annotation.Nonnull String eventType) {
    this.eventType = eventType;
    return this;
  }

  /**
   * Get eventType
   * @return eventType
   */
  @javax.annotation.Nonnull
  public String getEventType() {
    return eventType;
  }

  public void setEventType(@javax.annotation.Nonnull String eventType) {
    this.eventType = eventType;
  }


  public WebhookDeliveryResponse payload(@javax.annotation.Nonnull Object payload) {
    this.payload = payload;
    return this;
  }

  /**
   * Full JSON payload that was sent to the endpoint.
   * @return payload
   */
  @javax.annotation.Nonnull
  public Object getPayload() {
    return payload;
  }

  public void setPayload(@javax.annotation.Nonnull Object payload) {
    this.payload = payload;
  }


  public WebhookDeliveryResponse responseStatus(@javax.annotation.Nullable Integer responseStatus) {
    this.responseStatus = responseStatus;
    return this;
  }

  /**
   * HTTP status code returned by the endpoint, or null if the request failed to connect.
   * @return responseStatus
   */
  @javax.annotation.Nullable
  public Integer getResponseStatus() {
    return responseStatus;
  }

  public void setResponseStatus(@javax.annotation.Nullable Integer responseStatus) {
    this.responseStatus = responseStatus;
  }


  public WebhookDeliveryResponse responseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * First 1 KB of the response body.
   * @return responseBody
   */
  @javax.annotation.Nullable
  public String getResponseBody() {
    return responseBody;
  }

  public void setResponseBody(@javax.annotation.Nullable String responseBody) {
    this.responseBody = responseBody;
  }


  public WebhookDeliveryResponse durationMs(@javax.annotation.Nullable Integer durationMs) {
    this.durationMs = durationMs;
    return this;
  }

  /**
   * Round-trip time in milliseconds.
   * @return durationMs
   */
  @javax.annotation.Nullable
  public Integer getDurationMs() {
    return durationMs;
  }

  public void setDurationMs(@javax.annotation.Nullable Integer durationMs) {
    this.durationMs = durationMs;
  }


  public WebhookDeliveryResponse isSuccessful(@javax.annotation.Nonnull Boolean isSuccessful) {
    this.isSuccessful = isSuccessful;
    return this;
  }

  /**
   * True if the endpoint returned a 2xx status within 10 seconds.
   * @return isSuccessful
   */
  @javax.annotation.Nonnull
  public Boolean getIsSuccessful() {
    return isSuccessful;
  }

  public void setIsSuccessful(@javax.annotation.Nonnull Boolean isSuccessful) {
    this.isSuccessful = isSuccessful;
  }


  public WebhookDeliveryResponse attemptNumber(@javax.annotation.Nonnull Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
    return this;
  }

  /**
   * 1 for the original delivery, 2 for the automatic retry.
   * @return attemptNumber
   */
  @javax.annotation.Nonnull
  public Integer getAttemptNumber() {
    return attemptNumber;
  }

  public void setAttemptNumber(@javax.annotation.Nonnull Integer attemptNumber) {
    this.attemptNumber = attemptNumber;
  }


  public WebhookDeliveryResponse deliveredAt(@javax.annotation.Nonnull OffsetDateTime deliveredAt) {
    this.deliveredAt = deliveredAt;
    return this;
  }

  /**
   * Get deliveredAt
   * @return deliveredAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getDeliveredAt() {
    return deliveredAt;
  }

  public void setDeliveredAt(@javax.annotation.Nonnull OffsetDateTime deliveredAt) {
    this.deliveredAt = deliveredAt;
  }


  public WebhookDeliveryResponse redeliveryOfId(@javax.annotation.Nullable Integer redeliveryOfId) {
    this.redeliveryOfId = redeliveryOfId;
    return this;
  }

  /**
   * ID of the original delivery if this is a manual redeliver, otherwise null.
   * @return redeliveryOfId
   */
  @javax.annotation.Nullable
  public Integer getRedeliveryOfId() {
    return redeliveryOfId;
  }

  public void setRedeliveryOfId(@javax.annotation.Nullable Integer redeliveryOfId) {
    this.redeliveryOfId = redeliveryOfId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookDeliveryResponse webhookDeliveryResponse = (WebhookDeliveryResponse) o;
    return Objects.equals(this.id, webhookDeliveryResponse.id) &&
        Objects.equals(this.endpointId, webhookDeliveryResponse.endpointId) &&
        Objects.equals(this.eventType, webhookDeliveryResponse.eventType) &&
        Objects.equals(this.payload, webhookDeliveryResponse.payload) &&
        Objects.equals(this.responseStatus, webhookDeliveryResponse.responseStatus) &&
        Objects.equals(this.responseBody, webhookDeliveryResponse.responseBody) &&
        Objects.equals(this.durationMs, webhookDeliveryResponse.durationMs) &&
        Objects.equals(this.isSuccessful, webhookDeliveryResponse.isSuccessful) &&
        Objects.equals(this.attemptNumber, webhookDeliveryResponse.attemptNumber) &&
        Objects.equals(this.deliveredAt, webhookDeliveryResponse.deliveredAt) &&
        Objects.equals(this.redeliveryOfId, webhookDeliveryResponse.redeliveryOfId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, endpointId, eventType, payload, responseStatus, responseBody, durationMs, isSuccessful, attemptNumber, deliveredAt, redeliveryOfId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookDeliveryResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    eventType: ").append(toIndentedString(eventType)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    responseStatus: ").append(toIndentedString(responseStatus)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("    durationMs: ").append(toIndentedString(durationMs)).append("\n");
    sb.append("    isSuccessful: ").append(toIndentedString(isSuccessful)).append("\n");
    sb.append("    attemptNumber: ").append(toIndentedString(attemptNumber)).append("\n");
    sb.append("    deliveredAt: ").append(toIndentedString(deliveredAt)).append("\n");
    sb.append("    redeliveryOfId: ").append(toIndentedString(redeliveryOfId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("endpoint_id");
    openapiFields.add("event_type");
    openapiFields.add("payload");
    openapiFields.add("response_status");
    openapiFields.add("response_body");
    openapiFields.add("duration_ms");
    openapiFields.add("is_successful");
    openapiFields.add("attempt_number");
    openapiFields.add("delivered_at");
    openapiFields.add("redelivery_of_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("endpoint_id");
    openapiRequiredFields.add("event_type");
    openapiRequiredFields.add("payload");
    openapiRequiredFields.add("is_successful");
    openapiRequiredFields.add("attempt_number");
    openapiRequiredFields.add("delivered_at");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookDeliveryResponse
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookDeliveryResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookDeliveryResponse is not found in the empty JSON string", WebhookDeliveryResponse.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookDeliveryResponse.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebhookDeliveryResponse` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookDeliveryResponse.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("event_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `event_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("event_type").toString()));
      }
      if ((jsonObj.get("response_body") != null && !jsonObj.get("response_body").isJsonNull()) && !jsonObj.get("response_body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `response_body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("response_body").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookDeliveryResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookDeliveryResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookDeliveryResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookDeliveryResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookDeliveryResponse>() {
           @Override
           public void write(JsonWriter out, WebhookDeliveryResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookDeliveryResponse read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookDeliveryResponse given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookDeliveryResponse
   * @throws IOException if the JSON string is invalid with respect to WebhookDeliveryResponse
   */
  public static WebhookDeliveryResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookDeliveryResponse.class);
  }

  /**
   * Convert an instance of WebhookDeliveryResponse to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

