/*
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ai.agora.publicapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import ai.agora.publicapi.JSON;

/**
 * WebhookEndpointHealth
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-17T17:42:51.106071275Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class WebhookEndpointHealth {
  public static final String SERIALIZED_NAME_ENDPOINT_ID = "endpoint_id";
  @SerializedName(SERIALIZED_NAME_ENDPOINT_ID)
  @javax.annotation.Nonnull
  private Integer endpointId;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  @javax.annotation.Nonnull
  private URI url;

  public static final String SERIALIZED_NAME_IS_ENABLED = "is_enabled";
  @SerializedName(SERIALIZED_NAME_IS_ENABLED)
  @javax.annotation.Nonnull
  private Boolean isEnabled;

  public static final String SERIALIZED_NAME_TOTAL_DELIVERIES = "total_deliveries";
  @SerializedName(SERIALIZED_NAME_TOTAL_DELIVERIES)
  @javax.annotation.Nonnull
  private Integer totalDeliveries;

  public static final String SERIALIZED_NAME_SUCCESSFUL_DELIVERIES = "successful_deliveries";
  @SerializedName(SERIALIZED_NAME_SUCCESSFUL_DELIVERIES)
  @javax.annotation.Nonnull
  private Integer successfulDeliveries;

  public static final String SERIALIZED_NAME_FAILED_DELIVERIES = "failed_deliveries";
  @SerializedName(SERIALIZED_NAME_FAILED_DELIVERIES)
  @javax.annotation.Nonnull
  private Integer failedDeliveries;

  public static final String SERIALIZED_NAME_SUCCESS_RATE = "success_rate";
  @SerializedName(SERIALIZED_NAME_SUCCESS_RATE)
  @javax.annotation.Nullable
  private Float successRate;

  public static final String SERIALIZED_NAME_LAST_DELIVERY_AT = "last_delivery_at";
  @SerializedName(SERIALIZED_NAME_LAST_DELIVERY_AT)
  @javax.annotation.Nullable
  private OffsetDateTime lastDeliveryAt;

  public static final String SERIALIZED_NAME_LAST_DELIVERY_IS_SUCCESSFUL = "last_delivery_is_successful";
  @SerializedName(SERIALIZED_NAME_LAST_DELIVERY_IS_SUCCESSFUL)
  @javax.annotation.Nullable
  private Boolean lastDeliveryIsSuccessful;

  public static final String SERIALIZED_NAME_AVG_DURATION_MS = "avg_duration_ms";
  @SerializedName(SERIALIZED_NAME_AVG_DURATION_MS)
  @javax.annotation.Nullable
  private Float avgDurationMs;

  public WebhookEndpointHealth() {
  }

  public WebhookEndpointHealth endpointId(@javax.annotation.Nonnull Integer endpointId) {
    this.endpointId = endpointId;
    return this;
  }

  /**
   * Get endpointId
   * @return endpointId
   */
  @javax.annotation.Nonnull
  public Integer getEndpointId() {
    return endpointId;
  }

  public void setEndpointId(@javax.annotation.Nonnull Integer endpointId) {
    this.endpointId = endpointId;
  }


  public WebhookEndpointHealth url(@javax.annotation.Nonnull URI url) {
    this.url = url;
    return this;
  }

  /**
   * Get url
   * @return url
   */
  @javax.annotation.Nonnull
  public URI getUrl() {
    return url;
  }

  public void setUrl(@javax.annotation.Nonnull URI url) {
    this.url = url;
  }


  public WebhookEndpointHealth isEnabled(@javax.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Get isEnabled
   * @return isEnabled
   */
  @javax.annotation.Nonnull
  public Boolean getIsEnabled() {
    return isEnabled;
  }

  public void setIsEnabled(@javax.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public WebhookEndpointHealth totalDeliveries(@javax.annotation.Nonnull Integer totalDeliveries) {
    this.totalDeliveries = totalDeliveries;
    return this;
  }

  /**
   * Total number of delivery attempts recorded.
   * @return totalDeliveries
   */
  @javax.annotation.Nonnull
  public Integer getTotalDeliveries() {
    return totalDeliveries;
  }

  public void setTotalDeliveries(@javax.annotation.Nonnull Integer totalDeliveries) {
    this.totalDeliveries = totalDeliveries;
  }


  public WebhookEndpointHealth successfulDeliveries(@javax.annotation.Nonnull Integer successfulDeliveries) {
    this.successfulDeliveries = successfulDeliveries;
    return this;
  }

  /**
   * Deliveries that received a 2xx response within 10 seconds.
   * @return successfulDeliveries
   */
  @javax.annotation.Nonnull
  public Integer getSuccessfulDeliveries() {
    return successfulDeliveries;
  }

  public void setSuccessfulDeliveries(@javax.annotation.Nonnull Integer successfulDeliveries) {
    this.successfulDeliveries = successfulDeliveries;
  }


  public WebhookEndpointHealth failedDeliveries(@javax.annotation.Nonnull Integer failedDeliveries) {
    this.failedDeliveries = failedDeliveries;
    return this;
  }

  /**
   * Deliveries that timed out or received a non-2xx response.
   * @return failedDeliveries
   */
  @javax.annotation.Nonnull
  public Integer getFailedDeliveries() {
    return failedDeliveries;
  }

  public void setFailedDeliveries(@javax.annotation.Nonnull Integer failedDeliveries) {
    this.failedDeliveries = failedDeliveries;
  }


  public WebhookEndpointHealth successRate(@javax.annotation.Nullable Float successRate) {
    this.successRate = successRate;
    return this;
  }

  /**
   * Ratio of successful to total deliveries (0–1). Null if no deliveries yet.
   * @return successRate
   */
  @javax.annotation.Nullable
  public Float getSuccessRate() {
    return successRate;
  }

  public void setSuccessRate(@javax.annotation.Nullable Float successRate) {
    this.successRate = successRate;
  }


  public WebhookEndpointHealth lastDeliveryAt(@javax.annotation.Nullable OffsetDateTime lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
    return this;
  }

  /**
   * Timestamp of the most recent delivery attempt.
   * @return lastDeliveryAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getLastDeliveryAt() {
    return lastDeliveryAt;
  }

  public void setLastDeliveryAt(@javax.annotation.Nullable OffsetDateTime lastDeliveryAt) {
    this.lastDeliveryAt = lastDeliveryAt;
  }


  public WebhookEndpointHealth lastDeliveryIsSuccessful(@javax.annotation.Nullable Boolean lastDeliveryIsSuccessful) {
    this.lastDeliveryIsSuccessful = lastDeliveryIsSuccessful;
    return this;
  }

  /**
   * Outcome of the most recent delivery attempt.
   * @return lastDeliveryIsSuccessful
   */
  @javax.annotation.Nullable
  public Boolean getLastDeliveryIsSuccessful() {
    return lastDeliveryIsSuccessful;
  }

  public void setLastDeliveryIsSuccessful(@javax.annotation.Nullable Boolean lastDeliveryIsSuccessful) {
    this.lastDeliveryIsSuccessful = lastDeliveryIsSuccessful;
  }


  public WebhookEndpointHealth avgDurationMs(@javax.annotation.Nullable Float avgDurationMs) {
    this.avgDurationMs = avgDurationMs;
    return this;
  }

  /**
   * Average round-trip time in milliseconds across all recorded deliveries.
   * @return avgDurationMs
   */
  @javax.annotation.Nullable
  public Float getAvgDurationMs() {
    return avgDurationMs;
  }

  public void setAvgDurationMs(@javax.annotation.Nullable Float avgDurationMs) {
    this.avgDurationMs = avgDurationMs;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookEndpointHealth webhookEndpointHealth = (WebhookEndpointHealth) o;
    return Objects.equals(this.endpointId, webhookEndpointHealth.endpointId) &&
        Objects.equals(this.url, webhookEndpointHealth.url) &&
        Objects.equals(this.isEnabled, webhookEndpointHealth.isEnabled) &&
        Objects.equals(this.totalDeliveries, webhookEndpointHealth.totalDeliveries) &&
        Objects.equals(this.successfulDeliveries, webhookEndpointHealth.successfulDeliveries) &&
        Objects.equals(this.failedDeliveries, webhookEndpointHealth.failedDeliveries) &&
        Objects.equals(this.successRate, webhookEndpointHealth.successRate) &&
        Objects.equals(this.lastDeliveryAt, webhookEndpointHealth.lastDeliveryAt) &&
        Objects.equals(this.lastDeliveryIsSuccessful, webhookEndpointHealth.lastDeliveryIsSuccessful) &&
        Objects.equals(this.avgDurationMs, webhookEndpointHealth.avgDurationMs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endpointId, url, isEnabled, totalDeliveries, successfulDeliveries, failedDeliveries, successRate, lastDeliveryAt, lastDeliveryIsSuccessful, avgDurationMs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookEndpointHealth {\n");
    sb.append("    endpointId: ").append(toIndentedString(endpointId)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    totalDeliveries: ").append(toIndentedString(totalDeliveries)).append("\n");
    sb.append("    successfulDeliveries: ").append(toIndentedString(successfulDeliveries)).append("\n");
    sb.append("    failedDeliveries: ").append(toIndentedString(failedDeliveries)).append("\n");
    sb.append("    successRate: ").append(toIndentedString(successRate)).append("\n");
    sb.append("    lastDeliveryAt: ").append(toIndentedString(lastDeliveryAt)).append("\n");
    sb.append("    lastDeliveryIsSuccessful: ").append(toIndentedString(lastDeliveryIsSuccessful)).append("\n");
    sb.append("    avgDurationMs: ").append(toIndentedString(avgDurationMs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("endpoint_id");
    openapiFields.add("url");
    openapiFields.add("is_enabled");
    openapiFields.add("total_deliveries");
    openapiFields.add("successful_deliveries");
    openapiFields.add("failed_deliveries");
    openapiFields.add("success_rate");
    openapiFields.add("last_delivery_at");
    openapiFields.add("last_delivery_is_successful");
    openapiFields.add("avg_duration_ms");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("endpoint_id");
    openapiRequiredFields.add("url");
    openapiRequiredFields.add("is_enabled");
    openapiRequiredFields.add("total_deliveries");
    openapiRequiredFields.add("successful_deliveries");
    openapiRequiredFields.add("failed_deliveries");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to WebhookEndpointHealth
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!WebhookEndpointHealth.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in WebhookEndpointHealth is not found in the empty JSON string", WebhookEndpointHealth.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!WebhookEndpointHealth.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `WebhookEndpointHealth` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : WebhookEndpointHealth.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("url").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!WebhookEndpointHealth.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'WebhookEndpointHealth' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<WebhookEndpointHealth> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(WebhookEndpointHealth.class));

       return (TypeAdapter<T>) new TypeAdapter<WebhookEndpointHealth>() {
           @Override
           public void write(JsonWriter out, WebhookEndpointHealth value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public WebhookEndpointHealth read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of WebhookEndpointHealth given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of WebhookEndpointHealth
   * @throws IOException if the JSON string is invalid with respect to WebhookEndpointHealth
   */
  public static WebhookEndpointHealth fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, WebhookEndpointHealth.class);
  }

  /**
   * Convert an instance of WebhookEndpointHealth to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

