/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiKeyTokenRequest,
  ApiKeyTokenResponse,
  ErrorResponse,
} from '../models/index';
import {
    ApiKeyTokenRequestFromJSON,
    ApiKeyTokenRequestToJSON,
    ApiKeyTokenResponseFromJSON,
    ApiKeyTokenResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface LoginWithApiKeyRequest {
    apiKeyTokenRequest: ApiKeyTokenRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Logs in with a long-lived Agora API key and returns a short-lived bearer JWT. The API key is only sent to this endpoint and should not be used for normal API calls.
     * Log in with an API key
     */
    async loginWithApiKeyRaw(requestParameters: LoginWithApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiKeyTokenResponse>> {
        if (requestParameters['apiKeyTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'apiKeyTokenRequest',
                'Required parameter "apiKeyTokenRequest" was null or undefined when calling loginWithApiKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/api-key/token`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiKeyTokenRequestToJSON(requestParameters['apiKeyTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiKeyTokenResponseFromJSON(jsonValue));
    }

    /**
     * Logs in with a long-lived Agora API key and returns a short-lived bearer JWT. The API key is only sent to this endpoint and should not be used for normal API calls.
     * Log in with an API key
     */
    async loginWithApiKey(requestParameters: LoginWithApiKeyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiKeyTokenResponse> {
        const response = await this.loginWithApiKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
