/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  LeadUploadRequest,
  LeadUploadResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LeadUploadRequestFromJSON,
    LeadUploadRequestToJSON,
    LeadUploadResponseFromJSON,
    LeadUploadResponseToJSON,
} from '../models/index';

export interface UploadLeadsRequest {
    leadUploadRequest: LeadUploadRequest;
}

/**
 * 
 */
export class LeadsApi extends runtime.BaseAPI {

    /**
     * Uploads lead JSON into an authorized campaign using a short-lived bearer token obtained from API key exchange. Processing reuses Agora\'s contact upload pipeline.
     * Upload leads
     */
    async uploadLeadsRaw(requestParameters: UploadLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LeadUploadResponse>> {
        if (requestParameters['leadUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'leadUploadRequest',
                'Required parameter "leadUploadRequest" was null or undefined when calling uploadLeads().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/leads/upload`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LeadUploadRequestToJSON(requestParameters['leadUploadRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LeadUploadResponseFromJSON(jsonValue));
    }

    /**
     * Uploads lead JSON into an authorized campaign using a short-lived bearer token obtained from API key exchange. Processing reuses Agora\'s contact upload pipeline.
     * Upload leads
     */
    async uploadLeads(requestParameters: UploadLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LeadUploadResponse> {
        const response = await this.uploadLeadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
