/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  RegenerateSecretResponse,
  WebhookDeliveryResponse,
  WebhookEndpointCreate,
  WebhookEndpointResponse,
  WebhookEndpointUpdate,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RegenerateSecretResponseFromJSON,
    RegenerateSecretResponseToJSON,
    WebhookDeliveryResponseFromJSON,
    WebhookDeliveryResponseToJSON,
    WebhookEndpointCreateFromJSON,
    WebhookEndpointCreateToJSON,
    WebhookEndpointResponseFromJSON,
    WebhookEndpointResponseToJSON,
    WebhookEndpointUpdateFromJSON,
    WebhookEndpointUpdateToJSON,
} from '../models/index';

export interface CreateWebhookEndpointRequest {
    campaignId: number;
    webhookEndpointCreate: WebhookEndpointCreate;
}

export interface DeleteWebhookEndpointRequest {
    campaignId: number;
    endpointId: number;
}

export interface ListWebhookDeliveriesRequest {
    campaignId: number;
    endpointId: number;
    success?: boolean;
    limit?: number;
}

export interface ListWebhookEndpointsRequest {
    campaignId: number;
}

export interface ListWebhookEventTypesRequest {
    campaignId: number;
}

export interface RedeliverWebhookDeliveryRequest {
    campaignId: number;
    deliveryId: number;
}

export interface RegenerateWebhookSecretRequest {
    campaignId: number;
    endpointId: number;
}

export interface TestWebhookEndpointRequest {
    campaignId: number;
    endpointId: number;
}

export interface UpdateWebhookEndpointRequest {
    campaignId: number;
    endpointId: number;
    webhookEndpointUpdate: WebhookEndpointUpdate;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Registers a new webhook endpoint on a campaign. Returns the endpoint with its signing secret — store it securely, it will not be shown again.
     * Create a webhook endpoint
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        if (requestParameters['webhookEndpointCreate'] == null) {
            throw new runtime.RequiredError(
                'webhookEndpointCreate',
                'Required parameter "webhookEndpointCreate" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEndpointCreateToJSON(requestParameters['webhookEndpointCreate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Registers a new webhook endpoint on a campaign. Returns the endpoint with its signing secret — store it securely, it will not be shown again.
     * Create a webhook endpoint
     */
    async createWebhookEndpoint(requestParameters: CreateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponse> {
        const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Permanently deletes a webhook endpoint and all its delivery history.
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints/{endpoint_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Permanently deletes a webhook endpoint and all its delivery history.
     * Delete a webhook endpoint
     */
    async deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
    }

    /**
     * Returns the delivery history for a webhook endpoint, ordered by most recent first.
     * List deliveries for a webhook endpoint
     */
    async listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebhookDeliveryResponse>>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listWebhookDeliveries().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling listWebhookDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['success'] != null) {
            queryParameters['success'] = requestParameters['success'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints/{endpoint_id}/deliveries`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebhookDeliveryResponseFromJSON));
    }

    /**
     * Returns the delivery history for a webhook endpoint, ordered by most recent first.
     * List deliveries for a webhook endpoint
     */
    async listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebhookDeliveryResponse>> {
        const response = await this.listWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all webhook endpoints registered on a campaign.
     * List webhook endpoints
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebhookEndpointResponse>>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listWebhookEndpoints().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebhookEndpointResponseFromJSON));
    }

    /**
     * Returns all webhook endpoints registered on a campaign.
     * List webhook endpoints
     */
    async listWebhookEndpoints(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebhookEndpointResponse>> {
        const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * List webhook event types
     */
    async listWebhookEventTypesRaw(requestParameters: ListWebhookEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listWebhookEventTypes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/events`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * List webhook event types
     */
    async listWebhookEventTypes(requestParameters: ListWebhookEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listWebhookEventTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Re-sends a previously delivered (or failed) event to the original endpoint. Creates a new delivery record linked to the original via `redelivery_of_id`.
     * Redeliver a webhook delivery
     */
    async redeliverWebhookDeliveryRaw(requestParameters: RedeliverWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling redeliverWebhookDelivery().'
            );
        }

        if (requestParameters['deliveryId'] == null) {
            throw new runtime.RequiredError(
                'deliveryId',
                'Required parameter "deliveryId" was null or undefined when calling redeliverWebhookDelivery().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/deliveries/{delivery_id}/redeliver`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"delivery_id"}}`, encodeURIComponent(String(requestParameters['deliveryId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Re-sends a previously delivered (or failed) event to the original endpoint. Creates a new delivery record linked to the original via `redelivery_of_id`.
     * Redeliver a webhook delivery
     */
    async redeliverWebhookDelivery(requestParameters: RedeliverWebhookDeliveryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryResponse> {
        const response = await this.redeliverWebhookDeliveryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotates the HMAC-SHA256 signing secret for a webhook endpoint. The old secret stops working immediately. Store the new secret securely — it will not be shown again.
     * Regenerate the signing secret
     */
    async regenerateWebhookSecretRaw(requestParameters: RegenerateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegenerateSecretResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling regenerateWebhookSecret().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling regenerateWebhookSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints/{endpoint_id}/regenerate-secret`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegenerateSecretResponseFromJSON(jsonValue));
    }

    /**
     * Rotates the HMAC-SHA256 signing secret for a webhook endpoint. The old secret stops working immediately. Store the new secret securely — it will not be shown again.
     * Regenerate the signing secret
     */
    async regenerateWebhookSecret(requestParameters: RegenerateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegenerateSecretResponse> {
        const response = await this.regenerateWebhookSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Sends a synthetic `ping` event to the endpoint URL and records the delivery result. Useful for verifying connectivity and signature verification before going live.
     * Send a test ping to a webhook endpoint
     */
    async testWebhookEndpointRaw(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookDeliveryResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling testWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling testWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints/{endpoint_id}/test`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookDeliveryResponseFromJSON(jsonValue));
    }

    /**
     * Sends a synthetic `ping` event to the endpoint URL and records the delivery result. Useful for verifying connectivity and signature verification before going live.
     * Send a test ping to a webhook endpoint
     */
    async testWebhookEndpoint(requestParameters: TestWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookDeliveryResponse> {
        const response = await this.testWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates one or more fields on an existing webhook endpoint. Omitted fields are unchanged.
     * Update a webhook endpoint
     */
    async updateWebhookEndpointRaw(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointResponse>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['webhookEndpointUpdate'] == null) {
            throw new runtime.RequiredError(
                'webhookEndpointUpdate',
                'Required parameter "webhookEndpointUpdate" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/campaigns/{campaign_id}/webhooks/endpoints/{endpoint_id}`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WebhookEndpointUpdateToJSON(requestParameters['webhookEndpointUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointResponseFromJSON(jsonValue));
    }

    /**
     * Updates one or more fields on an existing webhook endpoint. Omitted fields are unchanged.
     * Update a webhook endpoint
     */
    async updateWebhookEndpoint(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointResponse> {
        const response = await this.updateWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
