/* tslint:disable */
/* eslint-disable */
/**
 * Agora Public API
 * Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  WebhookEndpointHealth,
  WebhookEndpointSummary,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    WebhookEndpointHealthFromJSON,
    WebhookEndpointHealthToJSON,
    WebhookEndpointSummaryFromJSON,
    WebhookEndpointSummaryToJSON,
} from '../models/index';

export interface GetWebhookEndpointHealthRequest {
    campaignId: number;
    endpointId: number;
}

export interface ListWebhookEndpointsRequest {
    campaignId: number;
}

export interface ListWebhookEventTypesRequest {
    campaignId: number;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Returns a delivery health snapshot for the endpoint: total/successful/failed delivery counts, success rate, last delivery timestamp, and average response time. Use this to monitor the reliability of your webhook integration — alert on a dropping success rate or a stale `last_delivery_at`. 
     * Get delivery health for a webhook endpoint
     */
    async getWebhookEndpointHealthRaw(requestParameters: GetWebhookEndpointHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WebhookEndpointHealth>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling getWebhookEndpointHealth().'
            );
        }

        if (requestParameters['endpointId'] == null) {
            throw new runtime.RequiredError(
                'endpointId',
                'Required parameter "endpointId" was null or undefined when calling getWebhookEndpointHealth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/webhooks/{campaign_id}/endpoints/{endpoint_id}/health`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))).replace(`{${"endpoint_id"}}`, encodeURIComponent(String(requestParameters['endpointId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WebhookEndpointHealthFromJSON(jsonValue));
    }

    /**
     * Returns a delivery health snapshot for the endpoint: total/successful/failed delivery counts, success rate, last delivery timestamp, and average response time. Use this to monitor the reliability of your webhook integration — alert on a dropping success rate or a stale `last_delivery_at`. 
     * Get delivery health for a webhook endpoint
     */
    async getWebhookEndpointHealth(requestParameters: GetWebhookEndpointHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WebhookEndpointHealth> {
        const response = await this.getWebhookEndpointHealthRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all webhook endpoints configured on a campaign. Does not include signing secrets — use the Agora dashboard to manage secrets.
     * List webhook endpoints
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<WebhookEndpointSummary>>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listWebhookEndpoints().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/webhooks/{campaign_id}/endpoints`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WebhookEndpointSummaryFromJSON));
    }

    /**
     * Returns all webhook endpoints configured on a campaign. Does not include signing secrets — use the Agora dashboard to manage secrets.
     * List webhook endpoints
     */
    async listWebhookEndpoints(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<WebhookEndpointSummary>> {
        const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * List webhook event types
     */
    async listWebhookEventTypesRaw(requestParameters: ListWebhookEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<string>>> {
        if (requestParameters['campaignId'] == null) {
            throw new runtime.RequiredError(
                'campaignId',
                'Required parameter "campaignId" was null or undefined when calling listWebhookEventTypes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/webhooks/{campaign_id}/events`.replace(`{${"campaign_id"}}`, encodeURIComponent(String(requestParameters['campaignId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Returns all event type strings that can be subscribed to on a webhook endpoint.
     * List webhook event types
     */
    async listWebhookEventTypes(requestParameters: ListWebhookEventTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<string>> {
        const response = await this.listWebhookEventTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
