/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpointSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointSummary{}

// WebhookEndpointSummary struct for WebhookEndpointSummary
type WebhookEndpointSummary struct {
	Id int32 `json:"id"`
	CampaignId int32 `json:"campaign_id"`
	// Destination URL events are delivered to.
	Url string `json:"url"`
	Description *string `json:"description,omitempty"`
	// Event types this endpoint is subscribed to.
	SubscribedEvents []string `json:"subscribed_events"`
	IsEnabled bool `json:"is_enabled"`
	CreatedAt time.Time `json:"created_at"`
	// Outcome of the most recent delivery attempt, or null if no deliveries yet.
	LastDeliveryIsSuccessful *bool `json:"last_delivery_is_successful,omitempty"`
}

type _WebhookEndpointSummary WebhookEndpointSummary

// NewWebhookEndpointSummary instantiates a new WebhookEndpointSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointSummary(id int32, campaignId int32, url string, subscribedEvents []string, isEnabled bool, createdAt time.Time) *WebhookEndpointSummary {
	this := WebhookEndpointSummary{}
	this.Id = id
	this.CampaignId = campaignId
	this.Url = url
	this.SubscribedEvents = subscribedEvents
	this.IsEnabled = isEnabled
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookEndpointSummaryWithDefaults instantiates a new WebhookEndpointSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointSummaryWithDefaults() *WebhookEndpointSummary {
	this := WebhookEndpointSummary{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookEndpointSummary) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookEndpointSummary) SetId(v int32) {
	o.Id = v
}

// GetCampaignId returns the CampaignId field value
func (o *WebhookEndpointSummary) GetCampaignId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetCampaignIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *WebhookEndpointSummary) SetCampaignId(v int32) {
	o.CampaignId = v
}

// GetUrl returns the Url field value
func (o *WebhookEndpointSummary) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointSummary) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WebhookEndpointSummary) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookEndpointSummary) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WebhookEndpointSummary) SetDescription(v string) {
	o.Description = &v
}

// GetSubscribedEvents returns the SubscribedEvents field value
func (o *WebhookEndpointSummary) GetSubscribedEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SubscribedEvents
}

// GetSubscribedEventsOk returns a tuple with the SubscribedEvents field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetSubscribedEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscribedEvents, true
}

// SetSubscribedEvents sets field value
func (o *WebhookEndpointSummary) SetSubscribedEvents(v []string) {
	o.SubscribedEvents = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *WebhookEndpointSummary) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *WebhookEndpointSummary) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookEndpointSummary) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookEndpointSummary) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetLastDeliveryIsSuccessful returns the LastDeliveryIsSuccessful field value if set, zero value otherwise.
func (o *WebhookEndpointSummary) GetLastDeliveryIsSuccessful() bool {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		var ret bool
		return ret
	}
	return *o.LastDeliveryIsSuccessful
}

// GetLastDeliveryIsSuccessfulOk returns a tuple with the LastDeliveryIsSuccessful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointSummary) GetLastDeliveryIsSuccessfulOk() (*bool, bool) {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		return nil, false
	}
	return o.LastDeliveryIsSuccessful, true
}

// HasLastDeliveryIsSuccessful returns a boolean if a field has been set.
func (o *WebhookEndpointSummary) HasLastDeliveryIsSuccessful() bool {
	if o != nil && !IsNil(o.LastDeliveryIsSuccessful) {
		return true
	}

	return false
}

// SetLastDeliveryIsSuccessful gets a reference to the given bool and assigns it to the LastDeliveryIsSuccessful field.
func (o *WebhookEndpointSummary) SetLastDeliveryIsSuccessful(v bool) {
	o.LastDeliveryIsSuccessful = &v
}

func (o WebhookEndpointSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["campaign_id"] = o.CampaignId
	toSerialize["url"] = o.Url
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["subscribed_events"] = o.SubscribedEvents
	toSerialize["is_enabled"] = o.IsEnabled
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.LastDeliveryIsSuccessful) {
		toSerialize["last_delivery_is_successful"] = o.LastDeliveryIsSuccessful
	}
	return toSerialize, nil
}

func (o *WebhookEndpointSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"campaign_id",
		"url",
		"subscribed_events",
		"is_enabled",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpointSummary := _WebhookEndpointSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpointSummary)

	if err != nil {
		return err
	}

	*o = WebhookEndpointSummary(varWebhookEndpointSummary)

	return err
}

type NullableWebhookEndpointSummary struct {
	value *WebhookEndpointSummary
	isSet bool
}

func (v NullableWebhookEndpointSummary) Get() *WebhookEndpointSummary {
	return v.value
}

func (v *NullableWebhookEndpointSummary) Set(val *WebhookEndpointSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointSummary(val *WebhookEndpointSummary) *NullableWebhookEndpointSummary {
	return &NullableWebhookEndpointSummary{value: val, isSet: true}
}

func (v NullableWebhookEndpointSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


