/*
Agora Public API

Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeadUploadRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeadUploadRequest{}

// LeadUploadRequest struct for LeadUploadRequest
type LeadUploadRequest struct {
	// Target campaign. Required for API-key-derived bearer tokens.
	CampaignId int32 `json:"campaign_id"`
	Source *string `json:"source,omitempty"`
	Leads []LeadInput `json:"leads"`
	Tags []string `json:"tags,omitempty"`
	SkipDuplicates *bool `json:"skip_duplicates,omitempty"`
	// Must be true to confirm the caller has permission to upload these contacts.
	ComplianceAcknowledged bool `json:"compliance_acknowledged"`
	DisclaimerVersion *string `json:"disclaimer_version,omitempty"`
}

type _LeadUploadRequest LeadUploadRequest

// NewLeadUploadRequest instantiates a new LeadUploadRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeadUploadRequest(campaignId int32, leads []LeadInput, complianceAcknowledged bool) *LeadUploadRequest {
	this := LeadUploadRequest{}
	this.CampaignId = campaignId
	var source string = "api"
	this.Source = &source
	this.Leads = leads
	var skipDuplicates bool = true
	this.SkipDuplicates = &skipDuplicates
	this.ComplianceAcknowledged = complianceAcknowledged
	var disclaimerVersion string = "v1.0"
	this.DisclaimerVersion = &disclaimerVersion
	return &this
}

// NewLeadUploadRequestWithDefaults instantiates a new LeadUploadRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeadUploadRequestWithDefaults() *LeadUploadRequest {
	this := LeadUploadRequest{}
	var source string = "api"
	this.Source = &source
	var skipDuplicates bool = true
	this.SkipDuplicates = &skipDuplicates
	var disclaimerVersion string = "v1.0"
	this.DisclaimerVersion = &disclaimerVersion
	return &this
}

// GetCampaignId returns the CampaignId field value
func (o *LeadUploadRequest) GetCampaignId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetCampaignIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *LeadUploadRequest) SetCampaignId(v int32) {
	o.CampaignId = v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *LeadUploadRequest) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *LeadUploadRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *LeadUploadRequest) SetSource(v string) {
	o.Source = &v
}

// GetLeads returns the Leads field value
func (o *LeadUploadRequest) GetLeads() []LeadInput {
	if o == nil {
		var ret []LeadInput
		return ret
	}

	return o.Leads
}

// GetLeadsOk returns a tuple with the Leads field value
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetLeadsOk() ([]LeadInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Leads, true
}

// SetLeads sets field value
func (o *LeadUploadRequest) SetLeads(v []LeadInput) {
	o.Leads = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *LeadUploadRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *LeadUploadRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *LeadUploadRequest) SetTags(v []string) {
	o.Tags = v
}

// GetSkipDuplicates returns the SkipDuplicates field value if set, zero value otherwise.
func (o *LeadUploadRequest) GetSkipDuplicates() bool {
	if o == nil || IsNil(o.SkipDuplicates) {
		var ret bool
		return ret
	}
	return *o.SkipDuplicates
}

// GetSkipDuplicatesOk returns a tuple with the SkipDuplicates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetSkipDuplicatesOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipDuplicates) {
		return nil, false
	}
	return o.SkipDuplicates, true
}

// HasSkipDuplicates returns a boolean if a field has been set.
func (o *LeadUploadRequest) HasSkipDuplicates() bool {
	if o != nil && !IsNil(o.SkipDuplicates) {
		return true
	}

	return false
}

// SetSkipDuplicates gets a reference to the given bool and assigns it to the SkipDuplicates field.
func (o *LeadUploadRequest) SetSkipDuplicates(v bool) {
	o.SkipDuplicates = &v
}

// GetComplianceAcknowledged returns the ComplianceAcknowledged field value
func (o *LeadUploadRequest) GetComplianceAcknowledged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ComplianceAcknowledged
}

// GetComplianceAcknowledgedOk returns a tuple with the ComplianceAcknowledged field value
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetComplianceAcknowledgedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComplianceAcknowledged, true
}

// SetComplianceAcknowledged sets field value
func (o *LeadUploadRequest) SetComplianceAcknowledged(v bool) {
	o.ComplianceAcknowledged = v
}

// GetDisclaimerVersion returns the DisclaimerVersion field value if set, zero value otherwise.
func (o *LeadUploadRequest) GetDisclaimerVersion() string {
	if o == nil || IsNil(o.DisclaimerVersion) {
		var ret string
		return ret
	}
	return *o.DisclaimerVersion
}

// GetDisclaimerVersionOk returns a tuple with the DisclaimerVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeadUploadRequest) GetDisclaimerVersionOk() (*string, bool) {
	if o == nil || IsNil(o.DisclaimerVersion) {
		return nil, false
	}
	return o.DisclaimerVersion, true
}

// HasDisclaimerVersion returns a boolean if a field has been set.
func (o *LeadUploadRequest) HasDisclaimerVersion() bool {
	if o != nil && !IsNil(o.DisclaimerVersion) {
		return true
	}

	return false
}

// SetDisclaimerVersion gets a reference to the given string and assigns it to the DisclaimerVersion field.
func (o *LeadUploadRequest) SetDisclaimerVersion(v string) {
	o.DisclaimerVersion = &v
}

func (o LeadUploadRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeadUploadRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaign_id"] = o.CampaignId
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	toSerialize["leads"] = o.Leads
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.SkipDuplicates) {
		toSerialize["skip_duplicates"] = o.SkipDuplicates
	}
	toSerialize["compliance_acknowledged"] = o.ComplianceAcknowledged
	if !IsNil(o.DisclaimerVersion) {
		toSerialize["disclaimer_version"] = o.DisclaimerVersion
	}
	return toSerialize, nil
}

func (o *LeadUploadRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"campaign_id",
		"leads",
		"compliance_acknowledged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeadUploadRequest := _LeadUploadRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeadUploadRequest)

	if err != nil {
		return err
	}

	*o = LeadUploadRequest(varLeadUploadRequest)

	return err
}

type NullableLeadUploadRequest struct {
	value *LeadUploadRequest
	isSet bool
}

func (v NullableLeadUploadRequest) Get() *LeadUploadRequest {
	return v.value
}

func (v *NullableLeadUploadRequest) Set(val *LeadUploadRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLeadUploadRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLeadUploadRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeadUploadRequest(val *LeadUploadRequest) *NullableLeadUploadRequest {
	return &NullableLeadUploadRequest{value: val, isSet: true}
}

func (v NullableLeadUploadRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeadUploadRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


