/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegenerateSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegenerateSecretResponse{}

// RegenerateSecretResponse struct for RegenerateSecretResponse
type RegenerateSecretResponse struct {
	// New HMAC-SHA256 signing secret. Store securely — not shown again.
	Secret string `json:"secret"`
}

type _RegenerateSecretResponse RegenerateSecretResponse

// NewRegenerateSecretResponse instantiates a new RegenerateSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegenerateSecretResponse(secret string) *RegenerateSecretResponse {
	this := RegenerateSecretResponse{}
	this.Secret = secret
	return &this
}

// NewRegenerateSecretResponseWithDefaults instantiates a new RegenerateSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegenerateSecretResponseWithDefaults() *RegenerateSecretResponse {
	this := RegenerateSecretResponse{}
	return &this
}

// GetSecret returns the Secret field value
func (o *RegenerateSecretResponse) GetSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Secret
}

// GetSecretOk returns a tuple with the Secret field value
// and a boolean to check if the value has been set.
func (o *RegenerateSecretResponse) GetSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Secret, true
}

// SetSecret sets field value
func (o *RegenerateSecretResponse) SetSecret(v string) {
	o.Secret = v
}

func (o RegenerateSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegenerateSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["secret"] = o.Secret
	return toSerialize, nil
}

func (o *RegenerateSecretResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegenerateSecretResponse := _RegenerateSecretResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegenerateSecretResponse)

	if err != nil {
		return err
	}

	*o = RegenerateSecretResponse(varRegenerateSecretResponse)

	return err
}

type NullableRegenerateSecretResponse struct {
	value *RegenerateSecretResponse
	isSet bool
}

func (v NullableRegenerateSecretResponse) Get() *RegenerateSecretResponse {
	return v.value
}

func (v *NullableRegenerateSecretResponse) Set(val *RegenerateSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRegenerateSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRegenerateSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegenerateSecretResponse(val *RegenerateSecretResponse) *NullableRegenerateSecretResponse {
	return &NullableRegenerateSecretResponse{value: val, isSet: true}
}

func (v NullableRegenerateSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegenerateSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


