/*
Agora Public API

Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiKeyTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiKeyTokenRequest{}

// ApiKeyTokenRequest struct for ApiKeyTokenRequest
type ApiKeyTokenRequest struct {
	// Agora API key. Never log or persist this value outside secure credential storage.
	ApiKey string `json:"api_key"`
}

type _ApiKeyTokenRequest ApiKeyTokenRequest

// NewApiKeyTokenRequest instantiates a new ApiKeyTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiKeyTokenRequest(apiKey string) *ApiKeyTokenRequest {
	this := ApiKeyTokenRequest{}
	this.ApiKey = apiKey
	return &this
}

// NewApiKeyTokenRequestWithDefaults instantiates a new ApiKeyTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiKeyTokenRequestWithDefaults() *ApiKeyTokenRequest {
	this := ApiKeyTokenRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *ApiKeyTokenRequest) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *ApiKeyTokenRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *ApiKeyTokenRequest) SetApiKey(v string) {
	o.ApiKey = v
}

func (o ApiKeyTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiKeyTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *ApiKeyTokenRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiKeyTokenRequest := _ApiKeyTokenRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiKeyTokenRequest)

	if err != nil {
		return err
	}

	*o = ApiKeyTokenRequest(varApiKeyTokenRequest)

	return err
}

type NullableApiKeyTokenRequest struct {
	value *ApiKeyTokenRequest
	isSet bool
}

func (v NullableApiKeyTokenRequest) Get() *ApiKeyTokenRequest {
	return v.value
}

func (v *NullableApiKeyTokenRequest) Set(val *ApiKeyTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiKeyTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiKeyTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiKeyTokenRequest(val *ApiKeyTokenRequest) *NullableApiKeyTokenRequest {
	return &NullableApiKeyTokenRequest{value: val, isSet: true}
}

func (v NullableApiKeyTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiKeyTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


