/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeadUploadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeadUploadResponse{}

// LeadUploadResponse struct for LeadUploadResponse
type LeadUploadResponse struct {
	Status string `json:"status"`
	ImportId string `json:"import_id"`
	ReceivedCount int32 `json:"received_count"`
	ValidCount int32 `json:"valid_count"`
	InvalidCount int32 `json:"invalid_count"`
	Errors []LeadUploadError `json:"errors"`
}

type _LeadUploadResponse LeadUploadResponse

// NewLeadUploadResponse instantiates a new LeadUploadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeadUploadResponse(status string, importId string, receivedCount int32, validCount int32, invalidCount int32, errors []LeadUploadError) *LeadUploadResponse {
	this := LeadUploadResponse{}
	this.Status = status
	this.ImportId = importId
	this.ReceivedCount = receivedCount
	this.ValidCount = validCount
	this.InvalidCount = invalidCount
	this.Errors = errors
	return &this
}

// NewLeadUploadResponseWithDefaults instantiates a new LeadUploadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeadUploadResponseWithDefaults() *LeadUploadResponse {
	this := LeadUploadResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *LeadUploadResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LeadUploadResponse) SetStatus(v string) {
	o.Status = v
}

// GetImportId returns the ImportId field value
func (o *LeadUploadResponse) GetImportId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImportId
}

// GetImportIdOk returns a tuple with the ImportId field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetImportIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImportId, true
}

// SetImportId sets field value
func (o *LeadUploadResponse) SetImportId(v string) {
	o.ImportId = v
}

// GetReceivedCount returns the ReceivedCount field value
func (o *LeadUploadResponse) GetReceivedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReceivedCount
}

// GetReceivedCountOk returns a tuple with the ReceivedCount field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetReceivedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReceivedCount, true
}

// SetReceivedCount sets field value
func (o *LeadUploadResponse) SetReceivedCount(v int32) {
	o.ReceivedCount = v
}

// GetValidCount returns the ValidCount field value
func (o *LeadUploadResponse) GetValidCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ValidCount
}

// GetValidCountOk returns a tuple with the ValidCount field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetValidCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ValidCount, true
}

// SetValidCount sets field value
func (o *LeadUploadResponse) SetValidCount(v int32) {
	o.ValidCount = v
}

// GetInvalidCount returns the InvalidCount field value
func (o *LeadUploadResponse) GetInvalidCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.InvalidCount
}

// GetInvalidCountOk returns a tuple with the InvalidCount field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetInvalidCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InvalidCount, true
}

// SetInvalidCount sets field value
func (o *LeadUploadResponse) SetInvalidCount(v int32) {
	o.InvalidCount = v
}

// GetErrors returns the Errors field value
func (o *LeadUploadResponse) GetErrors() []LeadUploadError {
	if o == nil {
		var ret []LeadUploadError
		return ret
	}

	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value
// and a boolean to check if the value has been set.
func (o *LeadUploadResponse) GetErrorsOk() ([]LeadUploadError, bool) {
	if o == nil {
		return nil, false
	}
	return o.Errors, true
}

// SetErrors sets field value
func (o *LeadUploadResponse) SetErrors(v []LeadUploadError) {
	o.Errors = v
}

func (o LeadUploadResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeadUploadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["import_id"] = o.ImportId
	toSerialize["received_count"] = o.ReceivedCount
	toSerialize["valid_count"] = o.ValidCount
	toSerialize["invalid_count"] = o.InvalidCount
	toSerialize["errors"] = o.Errors
	return toSerialize, nil
}

func (o *LeadUploadResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"import_id",
		"received_count",
		"valid_count",
		"invalid_count",
		"errors",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeadUploadResponse := _LeadUploadResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeadUploadResponse)

	if err != nil {
		return err
	}

	*o = LeadUploadResponse(varLeadUploadResponse)

	return err
}

type NullableLeadUploadResponse struct {
	value *LeadUploadResponse
	isSet bool
}

func (v NullableLeadUploadResponse) Get() *LeadUploadResponse {
	return v.value
}

func (v *NullableLeadUploadResponse) Set(val *LeadUploadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLeadUploadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLeadUploadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeadUploadResponse(val *LeadUploadResponse) *NullableLeadUploadResponse {
	return &NullableLeadUploadResponse{value: val, isSet: true}
}

func (v NullableLeadUploadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeadUploadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


