/*
Agora Public API

Public API-key-enabled Agora API surface. This contract intentionally excludes internal, admin, dashboard, Firebase-only, and interactive settings APIs.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeadUploadError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeadUploadError{}

// LeadUploadError struct for LeadUploadError
type LeadUploadError struct {
	Row int32 `json:"row"`
	Field NullableString `json:"field,omitempty"`
	Message string `json:"message"`
}

type _LeadUploadError LeadUploadError

// NewLeadUploadError instantiates a new LeadUploadError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeadUploadError(row int32, message string) *LeadUploadError {
	this := LeadUploadError{}
	this.Row = row
	this.Message = message
	return &this
}

// NewLeadUploadErrorWithDefaults instantiates a new LeadUploadError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeadUploadErrorWithDefaults() *LeadUploadError {
	this := LeadUploadError{}
	return &this
}

// GetRow returns the Row field value
func (o *LeadUploadError) GetRow() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Row
}

// GetRowOk returns a tuple with the Row field value
// and a boolean to check if the value has been set.
func (o *LeadUploadError) GetRowOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Row, true
}

// SetRow sets field value
func (o *LeadUploadError) SetRow(v int32) {
	o.Row = v
}

// GetField returns the Field field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LeadUploadError) GetField() string {
	if o == nil || IsNil(o.Field.Get()) {
		var ret string
		return ret
	}
	return *o.Field.Get()
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LeadUploadError) GetFieldOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Field.Get(), o.Field.IsSet()
}

// HasField returns a boolean if a field has been set.
func (o *LeadUploadError) HasField() bool {
	if o != nil && o.Field.IsSet() {
		return true
	}

	return false
}

// SetField gets a reference to the given NullableString and assigns it to the Field field.
func (o *LeadUploadError) SetField(v string) {
	o.Field.Set(&v)
}
// SetFieldNil sets the value for Field to be an explicit nil
func (o *LeadUploadError) SetFieldNil() {
	o.Field.Set(nil)
}

// UnsetField ensures that no value is present for Field, not even an explicit nil
func (o *LeadUploadError) UnsetField() {
	o.Field.Unset()
}

// GetMessage returns the Message field value
func (o *LeadUploadError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *LeadUploadError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *LeadUploadError) SetMessage(v string) {
	o.Message = v
}

func (o LeadUploadError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeadUploadError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["row"] = o.Row
	if o.Field.IsSet() {
		toSerialize["field"] = o.Field.Get()
	}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *LeadUploadError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"row",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeadUploadError := _LeadUploadError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeadUploadError)

	if err != nil {
		return err
	}

	*o = LeadUploadError(varLeadUploadError)

	return err
}

type NullableLeadUploadError struct {
	value *LeadUploadError
	isSet bool
}

func (v NullableLeadUploadError) Get() *LeadUploadError {
	return v.value
}

func (v *NullableLeadUploadError) Set(val *LeadUploadError) {
	v.value = val
	v.isSet = true
}

func (v NullableLeadUploadError) IsSet() bool {
	return v.isSet
}

func (v *NullableLeadUploadError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeadUploadError(val *LeadUploadError) *NullableLeadUploadError {
	return &NullableLeadUploadError{value: val, isSet: true}
}

func (v NullableLeadUploadError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeadUploadError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


