/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
)

// checks if the WebhookEndpointUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointUpdate{}

// WebhookEndpointUpdate struct for WebhookEndpointUpdate
type WebhookEndpointUpdate struct {
	// New destination URL.
	Url *string `json:"url,omitempty"`
	Description *string `json:"description,omitempty"`
	// Replaces the full subscribed event list.
	SubscribedEvents []string `json:"subscribed_events,omitempty"`
	IsEnabled *bool `json:"is_enabled,omitempty"`
}

// NewWebhookEndpointUpdate instantiates a new WebhookEndpointUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointUpdate() *WebhookEndpointUpdate {
	this := WebhookEndpointUpdate{}
	return &this
}

// NewWebhookEndpointUpdateWithDefaults instantiates a new WebhookEndpointUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointUpdateWithDefaults() *WebhookEndpointUpdate {
	this := WebhookEndpointUpdate{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *WebhookEndpointUpdate) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointUpdate) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *WebhookEndpointUpdate) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *WebhookEndpointUpdate) SetUrl(v string) {
	o.Url = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WebhookEndpointUpdate) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointUpdate) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookEndpointUpdate) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WebhookEndpointUpdate) SetDescription(v string) {
	o.Description = &v
}

// GetSubscribedEvents returns the SubscribedEvents field value if set, zero value otherwise.
func (o *WebhookEndpointUpdate) GetSubscribedEvents() []string {
	if o == nil || IsNil(o.SubscribedEvents) {
		var ret []string
		return ret
	}
	return o.SubscribedEvents
}

// GetSubscribedEventsOk returns a tuple with the SubscribedEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointUpdate) GetSubscribedEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.SubscribedEvents) {
		return nil, false
	}
	return o.SubscribedEvents, true
}

// HasSubscribedEvents returns a boolean if a field has been set.
func (o *WebhookEndpointUpdate) HasSubscribedEvents() bool {
	if o != nil && !IsNil(o.SubscribedEvents) {
		return true
	}

	return false
}

// SetSubscribedEvents gets a reference to the given []string and assigns it to the SubscribedEvents field.
func (o *WebhookEndpointUpdate) SetSubscribedEvents(v []string) {
	o.SubscribedEvents = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *WebhookEndpointUpdate) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointUpdate) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *WebhookEndpointUpdate) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *WebhookEndpointUpdate) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

func (o WebhookEndpointUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.SubscribedEvents) {
		toSerialize["subscribed_events"] = o.SubscribedEvents
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	return toSerialize, nil
}

type NullableWebhookEndpointUpdate struct {
	value *WebhookEndpointUpdate
	isSet bool
}

func (v NullableWebhookEndpointUpdate) Get() *WebhookEndpointUpdate {
	return v.value
}

func (v *NullableWebhookEndpointUpdate) Set(val *WebhookEndpointUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointUpdate(val *WebhookEndpointUpdate) *NullableWebhookEndpointUpdate {
	return &NullableWebhookEndpointUpdate{value: val, isSet: true}
}

func (v NullableWebhookEndpointUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


