/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpointHealth type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointHealth{}

// WebhookEndpointHealth struct for WebhookEndpointHealth
type WebhookEndpointHealth struct {
	EndpointId int32 `json:"endpoint_id"`
	Url string `json:"url"`
	IsEnabled bool `json:"is_enabled"`
	// Total number of delivery attempts recorded.
	TotalDeliveries int32 `json:"total_deliveries"`
	// Deliveries that received a 2xx response within 10 seconds.
	SuccessfulDeliveries int32 `json:"successful_deliveries"`
	// Deliveries that timed out or received a non-2xx response.
	FailedDeliveries int32 `json:"failed_deliveries"`
	// Ratio of successful to total deliveries (0–1). Null if no deliveries yet.
	SuccessRate *float32 `json:"success_rate,omitempty"`
	// Timestamp of the most recent delivery attempt.
	LastDeliveryAt *time.Time `json:"last_delivery_at,omitempty"`
	// Outcome of the most recent delivery attempt.
	LastDeliveryIsSuccessful *bool `json:"last_delivery_is_successful,omitempty"`
	// Average round-trip time in milliseconds across all recorded deliveries.
	AvgDurationMs *float32 `json:"avg_duration_ms,omitempty"`
}

type _WebhookEndpointHealth WebhookEndpointHealth

// NewWebhookEndpointHealth instantiates a new WebhookEndpointHealth object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointHealth(endpointId int32, url string, isEnabled bool, totalDeliveries int32, successfulDeliveries int32, failedDeliveries int32) *WebhookEndpointHealth {
	this := WebhookEndpointHealth{}
	this.EndpointId = endpointId
	this.Url = url
	this.IsEnabled = isEnabled
	this.TotalDeliveries = totalDeliveries
	this.SuccessfulDeliveries = successfulDeliveries
	this.FailedDeliveries = failedDeliveries
	return &this
}

// NewWebhookEndpointHealthWithDefaults instantiates a new WebhookEndpointHealth object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointHealthWithDefaults() *WebhookEndpointHealth {
	this := WebhookEndpointHealth{}
	return &this
}

// GetEndpointId returns the EndpointId field value
func (o *WebhookEndpointHealth) GetEndpointId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetEndpointIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *WebhookEndpointHealth) SetEndpointId(v int32) {
	o.EndpointId = v
}

// GetUrl returns the Url field value
func (o *WebhookEndpointHealth) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointHealth) SetUrl(v string) {
	o.Url = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *WebhookEndpointHealth) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *WebhookEndpointHealth) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetTotalDeliveries returns the TotalDeliveries field value
func (o *WebhookEndpointHealth) GetTotalDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalDeliveries
}

// GetTotalDeliveriesOk returns a tuple with the TotalDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetTotalDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalDeliveries, true
}

// SetTotalDeliveries sets field value
func (o *WebhookEndpointHealth) SetTotalDeliveries(v int32) {
	o.TotalDeliveries = v
}

// GetSuccessfulDeliveries returns the SuccessfulDeliveries field value
func (o *WebhookEndpointHealth) GetSuccessfulDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.SuccessfulDeliveries
}

// GetSuccessfulDeliveriesOk returns a tuple with the SuccessfulDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetSuccessfulDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SuccessfulDeliveries, true
}

// SetSuccessfulDeliveries sets field value
func (o *WebhookEndpointHealth) SetSuccessfulDeliveries(v int32) {
	o.SuccessfulDeliveries = v
}

// GetFailedDeliveries returns the FailedDeliveries field value
func (o *WebhookEndpointHealth) GetFailedDeliveries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FailedDeliveries
}

// GetFailedDeliveriesOk returns a tuple with the FailedDeliveries field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetFailedDeliveriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FailedDeliveries, true
}

// SetFailedDeliveries sets field value
func (o *WebhookEndpointHealth) SetFailedDeliveries(v int32) {
	o.FailedDeliveries = v
}

// GetSuccessRate returns the SuccessRate field value if set, zero value otherwise.
func (o *WebhookEndpointHealth) GetSuccessRate() float32 {
	if o == nil || IsNil(o.SuccessRate) {
		var ret float32
		return ret
	}
	return *o.SuccessRate
}

// GetSuccessRateOk returns a tuple with the SuccessRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetSuccessRateOk() (*float32, bool) {
	if o == nil || IsNil(o.SuccessRate) {
		return nil, false
	}
	return o.SuccessRate, true
}

// HasSuccessRate returns a boolean if a field has been set.
func (o *WebhookEndpointHealth) HasSuccessRate() bool {
	if o != nil && !IsNil(o.SuccessRate) {
		return true
	}

	return false
}

// SetSuccessRate gets a reference to the given float32 and assigns it to the SuccessRate field.
func (o *WebhookEndpointHealth) SetSuccessRate(v float32) {
	o.SuccessRate = &v
}

// GetLastDeliveryAt returns the LastDeliveryAt field value if set, zero value otherwise.
func (o *WebhookEndpointHealth) GetLastDeliveryAt() time.Time {
	if o == nil || IsNil(o.LastDeliveryAt) {
		var ret time.Time
		return ret
	}
	return *o.LastDeliveryAt
}

// GetLastDeliveryAtOk returns a tuple with the LastDeliveryAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetLastDeliveryAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastDeliveryAt) {
		return nil, false
	}
	return o.LastDeliveryAt, true
}

// HasLastDeliveryAt returns a boolean if a field has been set.
func (o *WebhookEndpointHealth) HasLastDeliveryAt() bool {
	if o != nil && !IsNil(o.LastDeliveryAt) {
		return true
	}

	return false
}

// SetLastDeliveryAt gets a reference to the given time.Time and assigns it to the LastDeliveryAt field.
func (o *WebhookEndpointHealth) SetLastDeliveryAt(v time.Time) {
	o.LastDeliveryAt = &v
}

// GetLastDeliveryIsSuccessful returns the LastDeliveryIsSuccessful field value if set, zero value otherwise.
func (o *WebhookEndpointHealth) GetLastDeliveryIsSuccessful() bool {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		var ret bool
		return ret
	}
	return *o.LastDeliveryIsSuccessful
}

// GetLastDeliveryIsSuccessfulOk returns a tuple with the LastDeliveryIsSuccessful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetLastDeliveryIsSuccessfulOk() (*bool, bool) {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		return nil, false
	}
	return o.LastDeliveryIsSuccessful, true
}

// HasLastDeliveryIsSuccessful returns a boolean if a field has been set.
func (o *WebhookEndpointHealth) HasLastDeliveryIsSuccessful() bool {
	if o != nil && !IsNil(o.LastDeliveryIsSuccessful) {
		return true
	}

	return false
}

// SetLastDeliveryIsSuccessful gets a reference to the given bool and assigns it to the LastDeliveryIsSuccessful field.
func (o *WebhookEndpointHealth) SetLastDeliveryIsSuccessful(v bool) {
	o.LastDeliveryIsSuccessful = &v
}

// GetAvgDurationMs returns the AvgDurationMs field value if set, zero value otherwise.
func (o *WebhookEndpointHealth) GetAvgDurationMs() float32 {
	if o == nil || IsNil(o.AvgDurationMs) {
		var ret float32
		return ret
	}
	return *o.AvgDurationMs
}

// GetAvgDurationMsOk returns a tuple with the AvgDurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointHealth) GetAvgDurationMsOk() (*float32, bool) {
	if o == nil || IsNil(o.AvgDurationMs) {
		return nil, false
	}
	return o.AvgDurationMs, true
}

// HasAvgDurationMs returns a boolean if a field has been set.
func (o *WebhookEndpointHealth) HasAvgDurationMs() bool {
	if o != nil && !IsNil(o.AvgDurationMs) {
		return true
	}

	return false
}

// SetAvgDurationMs gets a reference to the given float32 and assigns it to the AvgDurationMs field.
func (o *WebhookEndpointHealth) SetAvgDurationMs(v float32) {
	o.AvgDurationMs = &v
}

func (o WebhookEndpointHealth) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointHealth) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["endpoint_id"] = o.EndpointId
	toSerialize["url"] = o.Url
	toSerialize["is_enabled"] = o.IsEnabled
	toSerialize["total_deliveries"] = o.TotalDeliveries
	toSerialize["successful_deliveries"] = o.SuccessfulDeliveries
	toSerialize["failed_deliveries"] = o.FailedDeliveries
	if !IsNil(o.SuccessRate) {
		toSerialize["success_rate"] = o.SuccessRate
	}
	if !IsNil(o.LastDeliveryAt) {
		toSerialize["last_delivery_at"] = o.LastDeliveryAt
	}
	if !IsNil(o.LastDeliveryIsSuccessful) {
		toSerialize["last_delivery_is_successful"] = o.LastDeliveryIsSuccessful
	}
	if !IsNil(o.AvgDurationMs) {
		toSerialize["avg_duration_ms"] = o.AvgDurationMs
	}
	return toSerialize, nil
}

func (o *WebhookEndpointHealth) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endpoint_id",
		"url",
		"is_enabled",
		"total_deliveries",
		"successful_deliveries",
		"failed_deliveries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpointHealth := _WebhookEndpointHealth{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpointHealth)

	if err != nil {
		return err
	}

	*o = WebhookEndpointHealth(varWebhookEndpointHealth)

	return err
}

type NullableWebhookEndpointHealth struct {
	value *WebhookEndpointHealth
	isSet bool
}

func (v NullableWebhookEndpointHealth) Get() *WebhookEndpointHealth {
	return v.value
}

func (v *NullableWebhookEndpointHealth) Set(val *WebhookEndpointHealth) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointHealth) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointHealth) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointHealth(val *WebhookEndpointHealth) *NullableWebhookEndpointHealth {
	return &NullableWebhookEndpointHealth{value: val, isSet: true}
}

func (v NullableWebhookEndpointHealth) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointHealth) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


