/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookEndpointResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookEndpointResponse{}

// WebhookEndpointResponse struct for WebhookEndpointResponse
type WebhookEndpointResponse struct {
	Id int32 `json:"id"`
	CampaignId int32 `json:"campaign_id"`
	Url string `json:"url"`
	Description *string `json:"description,omitempty"`
	SubscribedEvents []string `json:"subscribed_events"`
	IsEnabled bool `json:"is_enabled"`
	CreatedAt time.Time `json:"created_at"`
	// Signing secret. Only returned on creation — store it securely.
	Secret *string `json:"secret,omitempty"`
	// Outcome of the most recent delivery attempt, or null if no deliveries yet.
	LastDeliveryIsSuccessful *bool `json:"last_delivery_is_successful,omitempty"`
}

type _WebhookEndpointResponse WebhookEndpointResponse

// NewWebhookEndpointResponse instantiates a new WebhookEndpointResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookEndpointResponse(id int32, campaignId int32, url string, subscribedEvents []string, isEnabled bool, createdAt time.Time) *WebhookEndpointResponse {
	this := WebhookEndpointResponse{}
	this.Id = id
	this.CampaignId = campaignId
	this.Url = url
	this.SubscribedEvents = subscribedEvents
	this.IsEnabled = isEnabled
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookEndpointResponseWithDefaults instantiates a new WebhookEndpointResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookEndpointResponseWithDefaults() *WebhookEndpointResponse {
	this := WebhookEndpointResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookEndpointResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookEndpointResponse) SetId(v int32) {
	o.Id = v
}

// GetCampaignId returns the CampaignId field value
func (o *WebhookEndpointResponse) GetCampaignId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CampaignId
}

// GetCampaignIdOk returns a tuple with the CampaignId field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetCampaignIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignId, true
}

// SetCampaignId sets field value
func (o *WebhookEndpointResponse) SetCampaignId(v int32) {
	o.CampaignId = v
}

// GetUrl returns the Url field value
func (o *WebhookEndpointResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *WebhookEndpointResponse) SetUrl(v string) {
	o.Url = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WebhookEndpointResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WebhookEndpointResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WebhookEndpointResponse) SetDescription(v string) {
	o.Description = &v
}

// GetSubscribedEvents returns the SubscribedEvents field value
func (o *WebhookEndpointResponse) GetSubscribedEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.SubscribedEvents
}

// GetSubscribedEventsOk returns a tuple with the SubscribedEvents field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetSubscribedEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SubscribedEvents, true
}

// SetSubscribedEvents sets field value
func (o *WebhookEndpointResponse) SetSubscribedEvents(v []string) {
	o.SubscribedEvents = v
}

// GetIsEnabled returns the IsEnabled field value
func (o *WebhookEndpointResponse) GetIsEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetIsEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsEnabled, true
}

// SetIsEnabled sets field value
func (o *WebhookEndpointResponse) SetIsEnabled(v bool) {
	o.IsEnabled = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *WebhookEndpointResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *WebhookEndpointResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *WebhookEndpointResponse) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *WebhookEndpointResponse) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *WebhookEndpointResponse) SetSecret(v string) {
	o.Secret = &v
}

// GetLastDeliveryIsSuccessful returns the LastDeliveryIsSuccessful field value if set, zero value otherwise.
func (o *WebhookEndpointResponse) GetLastDeliveryIsSuccessful() bool {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		var ret bool
		return ret
	}
	return *o.LastDeliveryIsSuccessful
}

// GetLastDeliveryIsSuccessfulOk returns a tuple with the LastDeliveryIsSuccessful field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookEndpointResponse) GetLastDeliveryIsSuccessfulOk() (*bool, bool) {
	if o == nil || IsNil(o.LastDeliveryIsSuccessful) {
		return nil, false
	}
	return o.LastDeliveryIsSuccessful, true
}

// HasLastDeliveryIsSuccessful returns a boolean if a field has been set.
func (o *WebhookEndpointResponse) HasLastDeliveryIsSuccessful() bool {
	if o != nil && !IsNil(o.LastDeliveryIsSuccessful) {
		return true
	}

	return false
}

// SetLastDeliveryIsSuccessful gets a reference to the given bool and assigns it to the LastDeliveryIsSuccessful field.
func (o *WebhookEndpointResponse) SetLastDeliveryIsSuccessful(v bool) {
	o.LastDeliveryIsSuccessful = &v
}

func (o WebhookEndpointResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookEndpointResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["campaign_id"] = o.CampaignId
	toSerialize["url"] = o.Url
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["subscribed_events"] = o.SubscribedEvents
	toSerialize["is_enabled"] = o.IsEnabled
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	if !IsNil(o.LastDeliveryIsSuccessful) {
		toSerialize["last_delivery_is_successful"] = o.LastDeliveryIsSuccessful
	}
	return toSerialize, nil
}

func (o *WebhookEndpointResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"campaign_id",
		"url",
		"subscribed_events",
		"is_enabled",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookEndpointResponse := _WebhookEndpointResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookEndpointResponse)

	if err != nil {
		return err
	}

	*o = WebhookEndpointResponse(varWebhookEndpointResponse)

	return err
}

type NullableWebhookEndpointResponse struct {
	value *WebhookEndpointResponse
	isSet bool
}

func (v NullableWebhookEndpointResponse) Get() *WebhookEndpointResponse {
	return v.value
}

func (v *NullableWebhookEndpointResponse) Set(val *WebhookEndpointResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookEndpointResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookEndpointResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookEndpointResponse(val *WebhookEndpointResponse) *NullableWebhookEndpointResponse {
	return &NullableWebhookEndpointResponse{value: val, isSet: true}
}

func (v NullableWebhookEndpointResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookEndpointResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


