/*
Agora Public API

Agora Public API. Authenticate with an API key and upload leads to authorized campaigns. Manage webhook endpoints to receive real-time event notifications.

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agorapublicapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the WebhookDeliveryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveryResponse{}

// WebhookDeliveryResponse struct for WebhookDeliveryResponse
type WebhookDeliveryResponse struct {
	Id int32 `json:"id"`
	EndpointId int32 `json:"endpoint_id"`
	EventType string `json:"event_type"`
	// Full JSON payload that was sent to the endpoint.
	Payload map[string]interface{} `json:"payload"`
	// HTTP status code returned by the endpoint, or null if the request failed to connect.
	ResponseStatus *int32 `json:"response_status,omitempty"`
	// First 1 KB of the response body.
	ResponseBody *string `json:"response_body,omitempty"`
	// Round-trip time in milliseconds.
	DurationMs *int32 `json:"duration_ms,omitempty"`
	// True if the endpoint returned a 2xx status within 10 seconds.
	IsSuccessful bool `json:"is_successful"`
	// 1 for the original delivery, 2 for the automatic retry.
	AttemptNumber int32 `json:"attempt_number"`
	DeliveredAt time.Time `json:"delivered_at"`
	// ID of the original delivery if this is a manual redeliver, otherwise null.
	RedeliveryOfId *int32 `json:"redelivery_of_id,omitempty"`
}

type _WebhookDeliveryResponse WebhookDeliveryResponse

// NewWebhookDeliveryResponse instantiates a new WebhookDeliveryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveryResponse(id int32, endpointId int32, eventType string, payload map[string]interface{}, isSuccessful bool, attemptNumber int32, deliveredAt time.Time) *WebhookDeliveryResponse {
	this := WebhookDeliveryResponse{}
	this.Id = id
	this.EndpointId = endpointId
	this.EventType = eventType
	this.Payload = payload
	this.IsSuccessful = isSuccessful
	this.AttemptNumber = attemptNumber
	this.DeliveredAt = deliveredAt
	return &this
}

// NewWebhookDeliveryResponseWithDefaults instantiates a new WebhookDeliveryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveryResponseWithDefaults() *WebhookDeliveryResponse {
	this := WebhookDeliveryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookDeliveryResponse) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookDeliveryResponse) SetId(v int32) {
	o.Id = v
}

// GetEndpointId returns the EndpointId field value
func (o *WebhookDeliveryResponse) GetEndpointId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.EndpointId
}

// GetEndpointIdOk returns a tuple with the EndpointId field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetEndpointIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndpointId, true
}

// SetEndpointId sets field value
func (o *WebhookDeliveryResponse) SetEndpointId(v int32) {
	o.EndpointId = v
}

// GetEventType returns the EventType field value
func (o *WebhookDeliveryResponse) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *WebhookDeliveryResponse) SetEventType(v string) {
	o.EventType = v
}

// GetPayload returns the Payload field value
func (o *WebhookDeliveryResponse) GetPayload() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetPayloadOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Payload, true
}

// SetPayload sets field value
func (o *WebhookDeliveryResponse) SetPayload(v map[string]interface{}) {
	o.Payload = v
}

// GetResponseStatus returns the ResponseStatus field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetResponseStatus() int32 {
	if o == nil || IsNil(o.ResponseStatus) {
		var ret int32
		return ret
	}
	return *o.ResponseStatus
}

// GetResponseStatusOk returns a tuple with the ResponseStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetResponseStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.ResponseStatus) {
		return nil, false
	}
	return o.ResponseStatus, true
}

// HasResponseStatus returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasResponseStatus() bool {
	if o != nil && !IsNil(o.ResponseStatus) {
		return true
	}

	return false
}

// SetResponseStatus gets a reference to the given int32 and assigns it to the ResponseStatus field.
func (o *WebhookDeliveryResponse) SetResponseStatus(v int32) {
	o.ResponseStatus = &v
}

// GetResponseBody returns the ResponseBody field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetResponseBody() string {
	if o == nil || IsNil(o.ResponseBody) {
		var ret string
		return ret
	}
	return *o.ResponseBody
}

// GetResponseBodyOk returns a tuple with the ResponseBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetResponseBodyOk() (*string, bool) {
	if o == nil || IsNil(o.ResponseBody) {
		return nil, false
	}
	return o.ResponseBody, true
}

// HasResponseBody returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasResponseBody() bool {
	if o != nil && !IsNil(o.ResponseBody) {
		return true
	}

	return false
}

// SetResponseBody gets a reference to the given string and assigns it to the ResponseBody field.
func (o *WebhookDeliveryResponse) SetResponseBody(v string) {
	o.ResponseBody = &v
}

// GetDurationMs returns the DurationMs field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetDurationMs() int32 {
	if o == nil || IsNil(o.DurationMs) {
		var ret int32
		return ret
	}
	return *o.DurationMs
}

// GetDurationMsOk returns a tuple with the DurationMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetDurationMsOk() (*int32, bool) {
	if o == nil || IsNil(o.DurationMs) {
		return nil, false
	}
	return o.DurationMs, true
}

// HasDurationMs returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasDurationMs() bool {
	if o != nil && !IsNil(o.DurationMs) {
		return true
	}

	return false
}

// SetDurationMs gets a reference to the given int32 and assigns it to the DurationMs field.
func (o *WebhookDeliveryResponse) SetDurationMs(v int32) {
	o.DurationMs = &v
}

// GetIsSuccessful returns the IsSuccessful field value
func (o *WebhookDeliveryResponse) GetIsSuccessful() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsSuccessful
}

// GetIsSuccessfulOk returns a tuple with the IsSuccessful field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetIsSuccessfulOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsSuccessful, true
}

// SetIsSuccessful sets field value
func (o *WebhookDeliveryResponse) SetIsSuccessful(v bool) {
	o.IsSuccessful = v
}

// GetAttemptNumber returns the AttemptNumber field value
func (o *WebhookDeliveryResponse) GetAttemptNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AttemptNumber
}

// GetAttemptNumberOk returns a tuple with the AttemptNumber field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetAttemptNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttemptNumber, true
}

// SetAttemptNumber sets field value
func (o *WebhookDeliveryResponse) SetAttemptNumber(v int32) {
	o.AttemptNumber = v
}

// GetDeliveredAt returns the DeliveredAt field value
func (o *WebhookDeliveryResponse) GetDeliveredAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DeliveredAt
}

// GetDeliveredAtOk returns a tuple with the DeliveredAt field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetDeliveredAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeliveredAt, true
}

// SetDeliveredAt sets field value
func (o *WebhookDeliveryResponse) SetDeliveredAt(v time.Time) {
	o.DeliveredAt = v
}

// GetRedeliveryOfId returns the RedeliveryOfId field value if set, zero value otherwise.
func (o *WebhookDeliveryResponse) GetRedeliveryOfId() int32 {
	if o == nil || IsNil(o.RedeliveryOfId) {
		var ret int32
		return ret
	}
	return *o.RedeliveryOfId
}

// GetRedeliveryOfIdOk returns a tuple with the RedeliveryOfId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveryResponse) GetRedeliveryOfIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RedeliveryOfId) {
		return nil, false
	}
	return o.RedeliveryOfId, true
}

// HasRedeliveryOfId returns a boolean if a field has been set.
func (o *WebhookDeliveryResponse) HasRedeliveryOfId() bool {
	if o != nil && !IsNil(o.RedeliveryOfId) {
		return true
	}

	return false
}

// SetRedeliveryOfId gets a reference to the given int32 and assigns it to the RedeliveryOfId field.
func (o *WebhookDeliveryResponse) SetRedeliveryOfId(v int32) {
	o.RedeliveryOfId = &v
}

func (o WebhookDeliveryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["endpoint_id"] = o.EndpointId
	toSerialize["event_type"] = o.EventType
	toSerialize["payload"] = o.Payload
	if !IsNil(o.ResponseStatus) {
		toSerialize["response_status"] = o.ResponseStatus
	}
	if !IsNil(o.ResponseBody) {
		toSerialize["response_body"] = o.ResponseBody
	}
	if !IsNil(o.DurationMs) {
		toSerialize["duration_ms"] = o.DurationMs
	}
	toSerialize["is_successful"] = o.IsSuccessful
	toSerialize["attempt_number"] = o.AttemptNumber
	toSerialize["delivered_at"] = o.DeliveredAt
	if !IsNil(o.RedeliveryOfId) {
		toSerialize["redelivery_of_id"] = o.RedeliveryOfId
	}
	return toSerialize, nil
}

func (o *WebhookDeliveryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"endpoint_id",
		"event_type",
		"payload",
		"is_successful",
		"attempt_number",
		"delivered_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookDeliveryResponse := _WebhookDeliveryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookDeliveryResponse)

	if err != nil {
		return err
	}

	*o = WebhookDeliveryResponse(varWebhookDeliveryResponse)

	return err
}

type NullableWebhookDeliveryResponse struct {
	value *WebhookDeliveryResponse
	isSet bool
}

func (v NullableWebhookDeliveryResponse) Get() *WebhookDeliveryResponse {
	return v.value
}

func (v *NullableWebhookDeliveryResponse) Set(val *WebhookDeliveryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveryResponse(val *WebhookDeliveryResponse) *NullableWebhookDeliveryResponse {
	return &NullableWebhookDeliveryResponse{value: val, isSet: true}
}

func (v NullableWebhookDeliveryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


